### PR TITLE
.Net: Fix for HuggingFaceChatCompletionService incorrect modification of model id

### LINKED ISSUE #6752: .Net: Bug: PromptExecutionSettings are frozen and cannot be modified.
**Describe the bug**
When I was using Kernel.CreateFunctionFromPrompt, I set parameters through HuggingFacePromptExecutionSettings, and an exception was thrown:
`System.InvalidOperationException: PromptExecutionSettings are frozen and cannot be modified.`

**To Reproduce**

Copy the code below into `Connectors.HuggingFace.UnitTests\HuggingFaceKernelBuilderExtensionsTests.cs` in the  sk-dotnet project, and then run the unit test.

```csharp
[Fact]
public async Task RunKernelFunctionWithHuggingFaceShouldRunCorrectlyAsync()
{
    Kernel kernel = Kernel.CreateBuilder()
        .AddHuggingFaceChatCompletion("model", new Uri("http://localhost:8080"))
        .Build();

    var kernelFunction = kernel.CreateFunctionFromPrompt("Write a C# Hello world", new HuggingFacePromptExecutionSettings
    {
        Temperature = 0.4f,
        TopP = 1
    });

    await foreach (var update in kernel.InvokeStreamingAsync<StreamingChatMessageContent>(kernelFunction))
    {
        if (update.Content is { Length: > 0 })
        {
            Console.Write(update.Content);
        }
    }
}
```

**Expected behavior**
The kernel function run success and return correctly  results.

**Screenshots**
image

**Platform**
 - OS: Windows 11
 - IDE: Visual Studio
 - Language: C#
 - Source:  The sk-dotnet source code.

### PR DESCRIPTION
**Pull request by markwallace-microsoft**
### Motivation and Context

`ModelId` cannot be changed in the prompt execution settings once they are frozen

Closes #6752 

### Contribution Checklist

- [ ] The code builds clean without any errors or warnings
- [x] The PR follows the [SK Contribution Guidelines](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md) and the [pre-submission formatting script](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md#development-scripts) raises no violations
- [ ] All unit tests pass, and I have added new tests where possible
- [ ] I didn't break anyone :smile:

### CODE REVIEW

**Review by dmytrostruk — APPROVED** [review]

File: dotnet/src/Connectors/Connectors.HuggingFace/Core/Models/ChatCompletionRequest.cs [hunk 1]
```diff
@@ -118,7 +119,7 @@ internal static ChatCompletionRequest FromChatHistoryAndExecutionSettings(ChatHi
             Temperature = executionSettings.Temperature,
             Stop = executionSettings.Stop,
             MaxTokens = executionSettings.MaxTokens,
-            Model = executionSettings.ModelId ?? TextGenerationInferenceDefaultModel,
+            Model = executionSettings.ModelId ?? modelId ?? TextGenerationInferenceDefaultModel,
```
Comment (RogerBarreto) [inline dotnet/src/Connectors/Connectors.HuggingFace/Core/Models/ChatCompletionRequest.cs:122]: If the model id is provided in the method I would assume it has priority.

```suggestion
            Model = modelId ?? executionSettings.ModelId ?? TextGenerationInferenceDefaultModel,
```

**Review by RogerBarreto — APPROVED** [review]

File: dotnet/src/Connectors/Connectors.HuggingFace/Core/Models/ChatCompletionRequest.cs (hunk 1 above)
Comment (markwallace-microsoft) [reply dotnet/src/Connectors/Connectors.HuggingFace/Core/Models/ChatCompletionRequest.cs:122]: Behaviour explained in the param doc: `<param name="modelId">Model id to use if value in prompt execution settings is not set.</param>`

1. `executionSettings.ModelId` is what was set when the service was invoked
2. `modelId` is what is configured for the service
3. `TextGenerationInferenceDefaultModel` is the fallback
