### PR TITLE
.Net: Respect custom ToolChoice and ParallelToolCallsEnabled options in OpenAIResponseAgent

### LINKED ISSUE #13253: .Net: Bug: Cannot disable parallel tool calling for OpenAIResponseAgent
**Describe the bug**
`ResponseCreationOptionsFactory` overrides `ParallelToolCallsEnabled` to true, making it impossible to disable parallel tool calling for OpenAIResponseAgent.

Recently, Azure OpenAI responses API has a bug or behavior change that blocks parallel function calling. A temporary workaround is to disable parallel function calling, but it is being forced by SK.

**Expected behavior**
The `ParallelToolCallsEnabled` should not be overridden. There should be an option to enable/disable parallel tool calling.

**Platform**
 - Language: C#
 - Source: NuGet package version 1.66.0
 - AI model: OpenAI:GPT-5
 - IDE: Visual Studio
 - OS: Windows

### PR DESCRIPTION
**Pull request by DeepAQ**
### Motivation and Context

Fixes #13253 by respecting custom `ToolChoice` and `ParallelToolCallsEnabled` options in `OpenAIResponseAgent`.

### Description

Previously, when creating `ResponseCreationOptions` for `OpenAIResponseAgent` with kernel plugins, `ToolChoice` will be set to `Auto` and `ParallelToolCallsEnabled` will be set to `true` regardless of the options provided when creating the agent.

This change fixes the problem by setting the default options only when they are not provided, respecting the custom options.

### Contribution Checklist

- [x] The code builds clean without any errors or warnings
- [x] The PR follows the [SK Contribution Guidelines](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md) and the [pre-submission formatting script](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md#development-scripts) raises no violations
- [x] All unit tests pass, and I have added new tests where possible
- [x] I didn't break anyone :smile:

### CODE REVIEW

File: dotnet/src/Agents/OpenAI/Internal/ResponseCreationOptionsFactory.cs [hunk 1]
```diff
@@ -60,8 +60,14 @@ internal static ResponseCreationOptions CreateOptions(
...
-            creationOptions.ToolChoice = ResponseToolChoice.CreateAutoChoice();
-            creationOptions.ParallelToolCallsEnabled = true;
+            if (creationOptions.ToolChoice == null)
+            {
+                creationOptions.ToolChoice = ResponseToolChoice.CreateAutoChoice();
+            }
+            if (!creationOptions.ParallelToolCallsEnabled.HasValue)
+            {
+                creationOptions.ParallelToolCallsEnabled = true;
+            }
```
Comment (markwallace-microsoft) [inline dotnet/src/Agents/OpenAI/Internal/ResponseCreationOptionsFactory.cs]: No need to set the parallel tool calls to be true as this is the default value.
https://platform.openai.com/docs/api-reference/responses/create#responses_create-parallel_tool_calls

File: dotnet/src/Agents/OpenAI/Internal/ResponseCreationOptionsFactory.cs [hunk 2]
```diff
@@ -60,8 +60,10 @@ internal static ResponseCreationOptions CreateOptions(
         if (responseTools is not null && responseTools.Any())
         {
             creationOptions.Tools.AddRange(responseTools);
-            creationOptions.ToolChoice = ResponseToolChoice.CreateAutoChoice();
-            creationOptions.ParallelToolCallsEnabled = true;
+            if (creationOptions.ToolChoice == null)
```
Comment (rogerbarreto) [inline dotnet/src/Agents/OpenAI/Internal/ResponseCreationOptionsFactory.cs]:
```suggestion
            if (creationOptions.ToolChoice is null)
```

**Review by markwallace-microsoft — APPROVED** [review]
