### PR TITLE
.Net: Don't allow function name/id to be overwritten with an empty string

### LINKED ISSUE #9567: Bug: The bug where FunctionCallContentBuilder constructs a FunctionName as empty.
**Describe the bug**
When the code reaches 
‘var functionResult = await functionCall.InvokeAsync(kernel);’, 

an error is reported: “The plugin collection does not contain a plugin and/or function with the specified names. Plugin name - ‘’, function name - ‘’.” 

I initially suspected that FunctionCallContentBuilder is resetting the previously assigned name to empty. The erroneous code is as follows:
       ‘ if (update.Name is string name) { (functionNamesByIndex ??= [])[update.FunctionCallIndex] = name; }’

For more details, see: https://github.com/microsoft/semantic-kernel/issues/9535

### PR DESCRIPTION
**Pull request by markwallace-microsoft**
### Motivation and Context

Closes #9567 

### Description

The fix handles the case where a streaming update contains an empty string for the function name. I haven't been able to reproduce the scenario where this happens and I have asked the issue creator for more information. The function name has a max size of 64 chars and when I use that the function isn't split over multiple streaming responses.

Referencing the approach shown here: https://community.openai.com/t/functions-calling-with-streaming/305742

### Contribution Checklist

- [ ] The code builds clean without any errors or warnings
- [ ] The PR follows the [SK Contribution Guidelines](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md) and the [pre-submission formatting script](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md#development-scripts) raises no violations
- [ ] All unit tests pass, and I have added new tests where possible
- [ ] I didn't break anyone :smile:

### CODE REVIEW

File: dotnet/src/SemanticKernel.Abstractions/Contents/FunctionCallContentBuilder.cs [hunk 1]
```diff
@@ -181,13 +181,13 @@ private static void TrackStreamingFunctionCallUpdate(StreamingFunctionCallUpdate
 
         // If we have an call id, ensure the index is being tracked. Even if it's not a function update,
         // we want to keep track of it so we can send back an error.
-        if (update.CallId is string id)
+        if (update.CallId is string id && !string.IsNullOrEmpty(id))
```
Comment (RogerBarreto) [inline dotnet/src/SemanticKernel.Abstractions/Contents/FunctionCallContentBuilder.cs:184]: I wonder if we should append instead of setting the name.

For arguments we append, if we append `empty` or `null` we won't lose information and will be compatible with multi chunk namings.

**Review by RogerBarreto — APPROVED** [review]

File: dotnet/src/SemanticKernel.Abstractions/Contents/FunctionCallContentBuilder.cs (hunk 1 above)
Comment (markwallace-microsoft) [reply dotnet/src/SemanticKernel.Abstractions/Contents/FunctionCallContentBuilder.cs:184]: Yeah, I had the same thought. I did some investigation and the function name is limit to 64 chars and doesn't seem to be streamed. This is the sample on the OpenAI forum https://community.openai.com/t/functions-calling-with-streaming/305742. note that it doesn't append the function name or if but it does the function arguments. We haven't had any feedback that developers are running into issues with streamed function names so I'm going to leave as is until we get information that this behaviour is needed.
