### PR TITLE
.Net Processes - Refactoring/expanding Process Sample02

### LINKED ISSUE #9836: .Net Process: Update Step02 Process Sample to make it more digestable

### LINKED ISSUE #9837: .Net: Bug: .Net Processes sometimes fail due cancellation token getting triggered twice when it was already disposed

### PR DESCRIPTION
**Pull request by esttenorio**
### Description

- Updating Sample 02 to expand the usage and show case how to refactor the same process by using subprocesses as steps.
- Improving README file with more details on this sample
- Add more unit tests for Process testing/improving comments

Fixes #9836 
Fixes #9837 

### Contribution Checklist

- [x] The code builds clean without any errors or warnings
- [x] The PR follows the [SK Contribution Guidelines](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md) and the [pre-submission formatting script](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md#development-scripts) raises no violations
- [x] All unit tests pass, and I have added new tests where possible
- [x] I didn't break anyone :smile:

### CODE REVIEW

File: dotnet/src/Experimental/Process.LocalRuntime/LocalProcess.cs [hunk 1]
```diff
@@ -324,6 +324,24 @@ private void EnqueueExternalMessages(Queue<ProcessMessage> messageChannel)
...
 
+    /// <summary>
+    /// Process public events to emit them externally at the same time as the internal events
+    /// </summary>
+    /// <param name="events">events to be used to process only the public events</param>
+    /// <returns>boolean with details if there were public events detected</returns>
+    private bool EmitPublicEvents(IEnumerable<ProcessEvent> events)
+    {
+        bool eventsChanged = false;
+        events?.Where(stepEvent => stepEvent.Visibility == KernelProcessEventVisibility.Public).ToList().ForEach(stepEvent =>
```
Comment (crickman) [inline dotnet/src/Experimental/Process.LocalRuntime/LocalProcess.cs:335]: Coding / Perf Nit - Re-allocating as a list is a little expensive as opposed to simply using `foreach` on `IEnumerable`.  True, if you already have a list, the Linq extension `ForEach` has performance equivalent to a basic `for`...but if you have to re-allocate just to use the extension then I question the value.

File: dotnet/src/Experimental/Process.LocalRuntime/LocalProcess.cs [hunk 2]
```diff
@@ -333,13 +351,27 @@ private void EnqueueExternalMessages(Queue<ProcessMessage> messageChannel)
     private void EnqueueStepMessages(LocalStep step, Queue<ProcessMessage> messageChannel)
     {
         var allStepEvents = step.GetAllEvents();
+        // alternative solution start
+        bool eventsChanged = this.EmitPublicEvents(allStepEvents);
+
+        if (eventsChanged)
+        {
+            var unprocessedEvents = allStepEvents.Where(stepEvent => stepEvent.Visibility != KernelProcessEventVisibility.Public).ToList();
```
Comment (crickman) [inline dotnet/src/Experimental/Process.LocalRuntime/LocalProcess.cs:359]: This might be a concatenated enumeration and avoid reallocating a collection.

File: dotnet/src/Experimental/Process.IntegrationTests.Shared/ProcessTests.cs [hunk 3]
```diff
@@ -272,6 +272,93 @@ public async Task StepAndFanInProcessAsync()
...
+
+        KernelProcess process = processBuilder.Build();
+
+        // Act
+        string testInput = "SomeData";
+        var processHandle = await this._fixture.StartProcessAsync(process, kernel, new KernelProcessEvent() { Id = EmitterStep.InputEvent, Data = testInput });
+        var processInfo = await processHandle.GetStateAsync();
+
+        // Assert
+        var outputStep = (processInfo.Steps.Where(s => s.State.Name == lastStepName).FirstOrDefault() as KernelProcessStepInfo).State as KernelProcessStepState<StepState>;
```
Comment (crickman) [inline dotnet/src/Experimental/Process.IntegrationTests.Shared/ProcessTests.cs:329]: `var outputStep = processInfo.Steps.FirstOrDefault(s => s.State.Name == lastStepName)?.State as KernelProcessStepState<StepState>;`

File: dotnet/src/Experimental/Process.LocalRuntime/LocalProcess.cs (hunk 2 above)
Comment (esttenorio) [reply dotnet/src/Experimental/Process.LocalRuntime/LocalProcess.cs]: removed this code

File: dotnet/src/Experimental/Process.LocalRuntime/LocalProcess.cs (hunk 1 above)
Comment (esttenorio) [reply dotnet/src/Experimental/Process.LocalRuntime/LocalProcess.cs]: removed this code too

File: dotnet/src/Experimental/Process.IntegrationTests.Shared/ProcessTests.cs (hunk 3 above)
Comment (esttenorio) [reply dotnet/src/Experimental/Process.IntegrationTests.Shared/ProcessTests.cs]: refactored and move the step state check to a common method used by all tests using this approach

**Review by crickman — APPROVED** [review]

**Review by alliscode — APPROVED** [review]
