### PR TITLE
.Net: Ensure Required Headers in Mistral ChatCompletion HttpClient

### LINKED ISSUE #11634: .NET: Bug: `extra-parameters` needed in HttpClient for Mistral
**Describe the bug**
I am getting a 400 bad request exception for Mistral chat completions when I don't specify an `HttpClient` with the following header
```csharp
DefaultRequestHeaders =
{
    {  "extra-parameters", "pass-through" },
}
```

**Expected behavior**

**To Reproduce**
Run reproducer code
https://github.com/williambohrmann3/SemanticKernelMistralBug/blob/master/Program.cs

**Expected behavior**
The `HttpRequest` parameter is marked as optional, so this header shouldn't be required. It should "just work".

**Platform**
 - Language: C#
 - Source: NuGet 1.47.0-alpha
 - AI model: MistralAI:mistral-large-latest
 - IDE: Visual Studio
 - OS: Windows

**Additional context**
Interestingly, Python devs using the Mistral connector for LangChain are getting the same error message.
https://learn.microsoft.com/en-us/answers/questions/2117664/my-mistral-large-2407-serverless-deployment-api-is

https://learn.microsoft.com/en-us/answers/questions/2113323/((detail-extra-parameters-(safe-prompt)-are-not-al

Deep in the stack trace, after enabling language runtime exceptions, my colleague found the following error
```text
Error code: 400 - {'detail': "Extra parameters ['n'] are not allowed when extra-parameters is not set or set to be 'error'. Set extra-parameters to 'pass-through' to pass to the model."}
```

### PR DESCRIPTION
**Pull request by shethaadit**
### Description
This PR addresses a known issue where omitting the `"extra-parameters": "pass-through"` header in `HttpClient` results in a `400 Bad Request` when calling Mistral chat completions.

- **Fixes a critical integration bug** by enforcing the required header at the extension level if not provided by the user.
- **Adds a unit test** to validate correct injection of the header, improving coverage and reliability for MistralAI scenarios.

These changes improve robustness, eliminate manual setup pitfalls, and enhance maintainability for developers integrating Mistral models.

### Contribution Checklist

- [Y] The code builds clean without any errors or warnings
- [Y] The PR follows the [SK Contribution Guidelines](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md) and the [pre-submission formatting script](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md#development-scripts) raises no violations
- [Y] All unit tests pass, and I have added new tests where possible
- [Y] I didn't break anyone :smile:

Fixes #11634

### CODE REVIEW

File: dotnet/src/Connectors/Connectors.MistralAI/MistralAIKernelBuilderExtensions.cs
Comment (RogerBarreto) [inline dotnet/src/Connectors/Connectors.MistralAI/MistralAIKernelBuilderExtensions.cs:1]: We should only add additional headers if no httpClient was provided in the extension method or no `HttpClient` was found in the serviceProvider.

The reason for that, is that we don't want to change the behavior of an existing `httpClient` provider by the caller that can be living in a uncontrolled environment (could be static) or be reused in different places.

For this I suggest checking

`(httpClient is null && serviceProvider?.GetService<HttpClient>() is null)`
If this is true, we add the header.

Comment (shethaadit) [reply dotnet/src/Connectors/Connectors.MistralAI/MistralAIKernelBuilderExtensions.cs:1]: I see, got it. Thank you for your suggestion @RogerBarreto. I have pushed the new commit.

File: dotnet/src/Connectors/Connectors.MistralAI.UnitTests/MistralAIExtensionTests.cs [hunk 1]
```diff
@@ -81,4 +83,31 @@ public void AddMistralTextEmbeddingGenerationToKernelBuilder()
         Assert.NotNull(service);
         Assert.IsType<MistralAITextEmbeddingGenerationService>(service);
     }
+
+    [Fact]
+    public void AddMistralChatCompletionInjectsExtraParametersHeader()
```
Comment (RogerBarreto) [inline dotnet/src/Connectors/Connectors.MistralAI.UnitTests/MistralAIExtensionTests.cs:88]: You will need to modify this test, because as your are now passing an httpClient it will fail, (it wont modify a provided one).

Suggestion would be to use reflection to capture the 

mistralService.Client._httpClient and see if it's default headers are set.

https://github.com/microsoft/semantic-kernel/blob/034cf6f21bd495a3379f95f2d99ae9056d3543bc/dotnet/src/Connectors/Connectors.MistralAI/Client/MistralClient.cs#L44

Comment (shethaadit) [reply dotnet/src/Connectors/Connectors.MistralAI.UnitTests/MistralAIExtensionTests.cs:89]: Resolved.

**Review by RogerBarreto — APPROVED** [review]

**Review by markwallace-microsoft — DISMISSED** [review]

**Comment by markwallace-microsoft** [comment]
@shethaadit Can you confirm you have enabled the integration tests locally and they all pass?

- https://github.com/microsoft/semantic-kernel/blob/main/dotnet/src/IntegrationTests/Connectors/MistralAI/ChatCompletion/MistralAIChatCompletionTests.cs
- https://github.com/microsoft/semantic-kernel/blob/main/dotnet/src/IntegrationTests/Connectors/MistralAI/TextEmbedding/MistralAITextEmbeddingTests.cs

**Review by markwallace-microsoft — COMMENTED** [review]
@shethaadit Can you confirm you have enabled the integration tests locally and they all pass?

- https://github.com/microsoft/semantic-kernel/blob/main/dotnet/src/IntegrationTests/Connectors/MistralAI/ChatCompletion/MistralAIChatCompletionTests.cs
- https://github.com/microsoft/semantic-kernel/blob/main/dotnet/src/IntegrationTests/Connectors/MistralAI/TextEmbedding/MistralAITextEmbeddingTests.cs

**Comment by RogerBarreto** [comment]
> Need confirmation the integration tests are passing

image

Just ran, and everything looks good against `mistral-large-latest` model.

**Review by markwallace-microsoft — APPROVED** [review]
