### PR TITLE
.Net: Bump ONNX to 0.5.2

### LINKED ISSUE #9628: .Net: Bug: Application crashes when using the ONNX connector and OnnxRuntimeGenAI v0.5.0 package
**Describe the bug**
It seems that the latest release of the OnnxRuntimeGenAI (v0.5.0) introduces additional checks to prevent resource leaks (see https://github.com/microsoft/onnxruntime-genai/pull/799). As a result, an application using the ONNX connector crashes when it shuts down if it references this version of the ONNXGenAI runtime.

**To Reproduce**

Add a reference to the **Microsoft.ML.OnnxRuntimeGenAI.DirectML** Version="**0.5.0**" package and run the following code:

``` C#
// using OgaHandle ogaHandle = new OgaHandle();   <<=== UNCOMMENT FOR ONNX RUNTIME LIBRARY SHUTDOWN

IKernelBuilder builder = Kernel.CreateBuilder();
builder.Services
    .AddOnnxRuntimeGenAIChatCompletion(
            modelId: "phi3.0",
            modelPath: "...PATH TO MODEL...");

IKernelBuilder kernelBuilder = builder.Services.AddKernel();

Kernel kernel = builder.Build();

IChatCompletionService chat = kernel.Services.GetRequiredService<IChatCompletionService>();
ChatHistory history = new();
history.AddUserMessage("Hi");

await foreach (var content in chat.GetStreamingChatMessageContentsAsync(history))
{
    Console.Write(content);
}

Console.WriteLine("\nDone!");

// (chat as IDisposable)?.Dispose();            <<=== UNCOMMENT TO PREVENT RESOURCE LEAKS
```

Running the code above produces the following output and then crashes:
```
Hello! How can I assist you today??
Done!
OGA Error: Shutdown must be called before process exit, please check the documentation for the proper API to call to ensure clean shutdown.
````

I found a workaround based on the changes found in this [PR](https://github.com/microsoft/onnxruntime-genai/pull/357). It seems that declaring (and disposing) an `OgaHandle` will ensure a proper shutdown. I couldn't find much information about it except for the comment "Responsible for cleaning up the library during shutdown" [here](https://github.com/microsoft/onnxruntime-genai/blob/2f2686feea75a8f6d56c09088adc1b051f9224d4/examples/c/src/phi3.cpp#L230-L231).

However, simply declaring an OgaHandle is still insufficient to ensure a clean shutdown. The ONNX connector must also be disposed before the application exits. Otherwise, it will still crash with the following output:

```
OGA Error: 1 instances of struct Generators::Model were leaked.
OGA Error: 1 instances of struct Generators::Tokenizer were leaked.
    Please see the documentation for the API being used to ensure proper cleanup.
```
**Platform**
 - OS: Windows
 - IDE: Visual Studio
 - Language: C#
 - Source: NuGet package version 1.28.0-alpha (ONNX connector)

### PR DESCRIPTION
**Pull request by RogerBarreto**
### Motivation and Context

- The Latest 0.5.0 package also requires the caller to handle the resources with the `OgaHandler` instance, when a service is instantiated this resource needs to be also present and exposed together with the service. Otherwise a message will be sent to the console and the application will crash before finishing.

- Resolves #9628

### CODE REVIEW

File: dotnet/samples/Concepts/ChatCompletion/Onnx_ChatCompletion.cs [hunk 1]
```diff
@@ -105,5 +105,7 @@ public async Task ChatPromptAsync()
         reply = await kernel.InvokePromptAsync(chatPrompt.ToString());
 
         Console.WriteLine(reply);
+
+        (kernel.GetRequiredService<IChatCompletionService>() as IDisposable)?.Dispose();
```
Comment (dmytrostruk) [inline dotnet/samples/Concepts/ChatCompletion/Onnx_ChatCompletion.cs:109]: I'm not sure if this should be a part of example, is this something that we recommend doing? Taking into account that `IChatCompletionService` is registered in DI container, should the container handle the disposal based on selected service lifecycle during registration?

**Review by dmytrostruk — APPROVED** [review]

File: dotnet/samples/Concepts/ChatCompletion/Onnx_ChatCompletion.cs (hunk 1 above)
Comment (RogerBarreto) [reply dotnet/samples/Concepts/ChatCompletion/Onnx_ChatCompletion.cs:109]: @dmytrostruk This is a non-conventional pattern introduced by Onnx Library 0.5.0, where if you leave the application / ends it without disposing the service, a message is sent to the console similar to this:

```
OGA Error: 1 instances of struct Generators::Model were leaked.
OGA Error: 1 instances of struct Generators::Tokenizer were leaked.
    Please see the documentation for the API being used to ensure proper cleanup.
```

The two instances above are part of the service, which is `IDisposable`.

Comment (RogerBarreto) [reply dotnet/samples/Concepts/ChatCompletion/Onnx_ChatCompletion.cs]: Changed internal implementation to resolve the root cause.

Comment (dmytrostruk) [reply dotnet/samples/Concepts/ChatCompletion/Onnx_ChatCompletion.cs]: @RogerBarreto Makes sense. Based on my understanding, this problem is related to console apps/test frameworks. Taking into account that `OnnxRuntimeGenAIChatCompletionService` is registered as singleton in this example, singleton objects are disposed when service provider is disposed, and in ASP.NET applications it is disposed automatically when the application is stopped/redeployed/restarted, while in console applications/test frameworks this process should be handled manually. 

The other problem is that `(kernel.GetRequiredService<IChatCompletionService>() as IDisposable)` doesn't necessarily return `OnnxRuntimeGenAIChatCompletionService` in case you have multiple `IChatCompletionService` registered and some of them are `IDisposable`, so you may accidentally dispose a wrong service.

Main goal would be to let users know that this manual disposal should happen in specific cases only and it should be done only when a resource is not needed anymore. 

Taking into account that this code is executed within a test lifecycle, we can define `Onnx_ChatCompletion` test class as `IDisposable` and then in `Dispose` method dispose not just one service, but entire service provider, which in turn should dispose all resources it contains, since it's not going to be used anymore when the test run ends:
```csharp
public void Dispose()
{
    // Dispose IServiceProvider
    if (this._serviceProvider is IDisposable disposable)
    {
        disposable.Dispose();
    }
}
```

**Review by dmytrostruk — APPROVED** [review]

**Comment by f2bo** [comment]
Doesn't this change mean that the model is reloaded into memory every time that you run an inference? This might take several seconds each time.

On the other hand, isn't having multiple OgaHandles, one for each service instance, a problem? It's not guaranteed that you will only have a singleton instance and disposing of one of the ONNX services will shut down the ONNX runtime for the process, so that all other services become invalid.

**Comment by RogerBarreto** [comment]
@f2bo This won't be merged as is, I will add some extra Unit Testing to ensure it doesn't affect the status-quo, for the moment recommend using the `ONNX Connector` with previous version of GenAI.

File: dotnet/samples/Demos/OnnxSimpleRAG/Program.cs [hunk 2]
```diff
@@ -29,6 +27,10 @@
 // Path to the vocab file your ONNX BGE-MICRO-V2 model
 var embeddingVocabPath = config["Onnx:EmbeddingVocabPath"]!;
 
+// After Onnx GenAI 0.5.0 before using any Onnx service is necessary to
+// Instantiate the OgaHandle class to track the resources used by the Onnx services
```
Comment (westey-m) [inline dotnet/samples/Demos/OnnxSimpleRAG/Program.cs:31]:
```suggestion
// If using Onnx GenAI 0.5.0 or later, the OgaHandle class must be used to track
// resources used by the Onnx services, before using any of the Onnx services.
```

**Review by markwallace-microsoft — APPROVED** [review]

**Review by westey-m — APPROVED** [review]

**Comment by f2bo** [comment]
Rather than relying on users to ensure that an OgaHandle is created and disposed, I wonder if you have any objections to the following change:

``` C#
public sealed class OnnxRuntimeGenAIChatCompletionService : IChatCompletionService, IDisposable
{
    ...
    private readonly static OgaHandle s_ogaHandle = new();

    static OnnxRuntimeGenAIChatCompletionService()
        => AppDomain.CurrentDomain.ProcessExit += (_, _) => s_ogaHandle.Dispose();
  ...
}
```

**Comment by RogerBarret0** [comment]
@f2bo Yes, I personally object this approach as this injects static resources and behavior on customers environment/application domain without their knowledge to handle a non-conventional resource monitoring.

**Review by markwallace-microsoft — APPROVED** [review]
