### PR TITLE
Python: .Net: Add function calling with AzureAIInference sample

### LINKED ISSUE #9933: .Net: Bug: Azure-hosted Open-Source Models (e.g., Mistral Nemo) fail with Kernel Functions in .NET
**Describe the bug**  
Semantic Kernel Functions in .NET using `Microsoft.SemanticKernel.Connectors.AzureAIInference` do not work with Azure-hosted open-source models like "Mistral Nemo," even though these models support Function Calls. The same setup works fine with GPT models, and in Python, it works with Azure AI without any issues. This seems to be a .NET-specific issue with Semantic Kernel.  

**To Reproduce**  
1. Deploy an open-source model (e.g., "Mistral Nemo") in Azure AI.  
2. Integrate the connector `Microsoft.SemanticKernel.Connectors.AzureAIInference`.  
3. Use `PromptExecutionSettings` with `FunctionChoiceBehavior.Auto()`.  
4. Implement and execute a Semantic Kernel Function.  

**Expected behavior**  
The Semantic Kernel Function should execute successfully using Function Calls with the Azure-hosted open-source model, similar to how it works with GPT models or with Python implementations.  

**Screenshots**  
_Not applicable_  

**Platform**  
- OS: Windows  
- IDE: Visual Studio 2022  
- Language: C#  
- Source:  
  - Semantic Kernel version: 1.32.0  
  - Microsoft.SemanticKernel.Connectors.AzureAIInference version: 1.32.0-beta  

**Additional context**  
- The same functions work locally with models like LM Studio (Beta) or Ollama.  
- In Python, Function Calls with Azure-hosted models work as expected.  
- This issue seems specific to the Semantic Kernel in .NET when using Azure AI.  

Please provide guidance or a fix to enable Semantic Kernel Functions to work with Azure-hosted open-source models.

### PR DESCRIPTION
**Pull request by markwallace-microsoft**
### Motivation and Context

- Closes #9933 

### Contribution Checklist

- [ ] The code builds clean without any errors or warnings
- [ ] The PR follows the [SK Contribution Guidelines](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md) and the [pre-submission formatting script](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md#development-scripts) raises no violations
- [ ] All unit tests pass, and I have added new tests where possible
- [ ] I didn't break anyone :smile:

### CODE REVIEW

**Review by dmytrostruk — APPROVED** [review]

File: dotnet/src/Connectors/Connectors.AzureAIInference/Settings/AzureAIInferencePromptExecutionSettings.cs [hunk 1]
```diff
@@ -273,8 +273,8 @@ public static AzureAIInferencePromptExecutionSettings FromExecutionSettings(Prom
     private float? _nucleusSamplingFactor;
     private int? _maxTokens;
     private object? _responseFormat;
-    private IList<string> _stopSequences = [];
-    private IList<ChatCompletionsToolDefinition> _tools = [];
+    private IList<string>? _stopSequences;
+    private IList<ChatCompletionsToolDefinition>? _tools;
```
Comment (markwallace-microsoft) [inline dotnet/src/Connectors/Connectors.AzureAIInference/Settings/AzureAIInferencePromptExecutionSettings.cs:277]: Initialising tools to an empty array causes a Problem in the JSON payload.

@RogerBarreto  Is there a reason why this is being initialised to an empty array?

**Review by moonbox3 — APPROVED** [review]
Approving the Python concept sample typo fix. Thanks @markwallace-microsoft.

File: dotnet/src/Connectors/Connectors.AzureAIInference/Settings/AzureAIInferencePromptExecutionSettings.cs (hunk 1 above)
Comment (RogerBarreto) [reply dotnet/src/Connectors/Connectors.AzureAIInference/Settings/AzureAIInferencePromptExecutionSettings.cs:277]: No reason in specific, it should be expected the API's to handle null/empty arrays with no problem, but to reduce unneeded payload and avoid backend bugs on their API I'm totally fine changing this logic to be nullable by default.
