### PR TITLE
.Net: Update {Azure}OpenAI Connectors to latest 2.2.0-beta.1

### LINKED ISSUE #9749: .Net: Bug: SemanticKernel does not support Azure o1 series models
**Describe the bug**
The latest library of SemanticKernel does not support Azure o1 series models.
Reason for error: Unsupported parameter: 'max_tokens' is not supported with this model Use 'max_completion_tokens' instead.

**To Reproduce**
```
static async Task Main(string[] args)
{
    var kernel = Kernel.CreateBuilder()
        .AddAzureOpenAIChatCompletion(
            "deploy",
            "endpoint",
            "key"
        ).Build();

    KernelArguments arguments = new(new AzureOpenAIPromptExecutionSettings() { MaxTokens = 4096});
    Console.WriteLine(await kernel.InvokePromptAsync("What is the Semantic Kernel? Include citations to the relevant information where it is referenced in the response.", arguments));
}
```

**Platform**
 - OS: windows
 - IDE: Visual Studio
 - Language: C#
 - Source: NuGet package version 1.29.0

**Additional context**

Microsoft.SemanticKernel.HttpOperationException
  HResult=0x80131500
  Message=HTTP 400 (invalid_request_error: unsupported_parameter)
Parameter: max_tokens

Unsupported parameter: 'max_tokens' is not supported with this model. Use 'max_completion_tokens' instead.
  Source=Microsoft.SemanticKernel.Connectors.OpenAI
  スタック トレース:
   場所 Microsoft.SemanticKernel.Connectors.OpenAI.ClientCore.<RunRequestAsync>d__73`1.MoveNext()
   場所 Microsoft.SemanticKernel.Connectors.OpenAI.ClientCore.<GetChatMessageContentsAsync>d__16.MoveNext()
   場所 Microsoft.SemanticKernel.KernelFunctionFromPrompt.<GetChatCompletionResultAsync>d__25.MoveNext()
   場所 Microsoft.SemanticKernel.KernelFunctionFromPrompt.<InvokeCoreAsync>d__6.MoveNext()
   場所 System.Threading.Tasks.ValueTask`1.get_Result()
   場所 Microsoft.SemanticKernel.KernelFunction.<>c__DisplayClass27_0.<<InvokeAsync>b__0>d.MoveNext()
   場所 Microsoft.SemanticKernel.Kernel.<InvokeFilterOrFunctionAsync>d__34.MoveNext()
   場所 Microsoft.SemanticKernel.Kernel.<OnFunctionInvocationAsync>d__33.MoveNext()
   場所 Microsoft.SemanticKernel.KernelFunction.<InvokeAsync>d__27.MoveNext()
   場所 AOAI.Program.<Main>d__0.MoveNext() (D:\sandbox\AOAI\Program.cs):行 35

  この例外は、最初にこの呼び出し履歴 
    [外部コード] でスローされました

内部例外 1:
ClientResultException: HTTP 400 (invalid_request_error: unsupported_parameter)
Parameter: max_tokens

Unsupported parameter: 'max_tokens' is not supported with this model. Use 'max_completion_tokens' instead.

### LINKED ISSUE #10201: .Net: Bug: SK can't call AzureOpenAI o1/o3-mini models
**Describe the bug**
When doing an agent.InvokeAsync call against the o1 model (version:2024-12-17) in Azure Open AI service you get error:

`"HTTP 400 (BadRequest)\r\n\r\nModel o1 is enabled only for api versions 2024-12-01-preview and later" `

**To Reproduce**
1. Make a kernel chat completion service that target o1 as deployment model
2. Make an agent (with instructions, temperature and structured output)
3. Call agent.InvokeAsync

**Expected behavior**
A normal LLM respose (in this case json due to structured output)

**Platform**
 - OS: Windows
 - IDE: Visual Studio
 - Language: C#
 - Source: NuGet package version 1.33.0

**Additional context**
Issue is properly the transative use of the azure.ai.openai beta2 package. I tried manually bumping this to latest, but it gave an feature not implemented exception

### LINKED ISSUE #10367: .Net: New Feature: Support for reasoning_effort parameter in .NET
---
name: Support for reasoning_effort parameter in .NET
about: The o1 and o3-mini models have added a new reasoning_effort parameter. In order to use the o3-mini-high model this parameter needs to be supported and set to high.

https://platform.openai.com/docs/guides/reasoning

---

### LINKED ISSUE #10484: .Net: Update Both (OpenAI + AzureOpenAI) Connectors to use 2.2.0-beta.1 version.
With the last week release of the latest version of the SDK's we need to update our connectors so this might add support to the new `o1` and `o3` models, latest api version `2025-01-01-preview`, ` AudioContent` in Chat History and more.

### PR DESCRIPTION
**Pull request by RogerBarreto**
### Motivation and Context

- Resolves #10484 
- Resolves #10367
- Resolves #10201
- Resolves #9749

Some Azure Backend API's may not fully work with the latest SDK updates, but this is rather a limitation of the backend not related to the SDK itself.

- Some model and Azure OpenAI endpoints trigger error for both `system` and `developer` roles, only accepting `user`.
- Attempting to use temperature parameters in reasoning models (o1+) is not supported in the backends
- Some backend models may still reject the `reasoning_effort` parameter. (o1-mini)

### CODE REVIEW

**Comment by dmytrostruk** [comment]
@RogerBarreto FYI there is already existing community PR to update {Azure}OpenAI package versions: https://github.com/microsoft/semantic-kernel/pull/10487

But it looks like your PR has more changes, feel free to decide which PR should be merged. Thanks!

**Comment by rwjdk** [comment]
It makes sense that 01-mini will not work... The model version is still pre-full release (It's from September last year)

image

File: dotnet/src/SemanticKernel.Abstractions/AI/ChatCompletion/ChatHistory.cs [hunk 1]
```diff
@@ -31,12 +31,20 @@ public ChatHistory()
     /// Creates a new instance of the <see cref="ChatHistory"/> class with a system message
```
Comment (markwallace-microsoft) [inline dotnet/src/SemanticKernel.Abstractions/AI/ChatCompletion/ChatHistory.cs:31]: Creates a new instance of the <see cref="ChatHistory"/> class with a single message using the role provided. If not role is provided then this will be a system message.

File: dotnet/src/SemanticKernel.Abstractions/AI/ChatCompletion/ChatHistory.cs [hunk 2]
```diff
@@ -31,12 +31,20 @@ public ChatHistory()
...
     /// </summary>
     /// <param name="systemMessage">The system message to add to the history.</param>
-    public ChatHistory(string systemMessage)
+    /// <param name="role">Optional role to add as the first message. Defaults to system message</param>
+    public ChatHistory(string systemMessage, AuthorRole? role = null)
```
Comment (markwallace-microsoft) [inline dotnet/src/SemanticKernel.Abstractions/AI/ChatCompletion/ChatHistory.cs:35]: Should the default role be the system role and then the code below can be simplified.

**Review by markwallace-microsoft — COMMENTED** [review]
LGTM but PR is failing required checks.

File: dotnet/src/Connectors/Connectors.OpenAI/Settings/OpenAIPromptExecutionSettings.cs [hunk 3]
```diff
@@ -414,11 +455,13 @@ public static OpenAIPromptExecutionSettings FromExecutionSettings(PromptExecutio
             TopLogprobs = this.TopLogprobs,
             Store = this.Store,
             Metadata = this.Metadata is not null ? new Dictionary<string, string>(this.Metadata) : null,
+            ReasoningEffort = this.ReasoningEffort
```
Comment (SergeyMenshykh) [inline dotnet/src/Connectors/Connectors.OpenAI/Settings/OpenAIPromptExecutionSettings.cs:458]: The ChatDeveloperPrompt should be cloned as well, shouldn't it?

File: dotnet/src/SemanticKernel.Abstractions/AI/ChatCompletion/ChatHistory.cs [hunk 4]
```diff
@@ -28,15 +28,24 @@ public ChatHistory()
...
     /// <summary>
-    /// Creates a new instance of the <see cref="ChatHistory"/> class with a system message
+    /// Creates a new instance of the <see cref="ChatHistory"/> with a single message using an optional role.
+    /// If not role is provided then the first message will default to <see cref="AuthorRole.System"/> role.
     /// </summary>
-    /// <param name="systemMessage">The system message to add to the history.</param>
-    public ChatHistory(string systemMessage)
+    /// <param name="systemMessage">The text message to add to the first message in chat history.</param>
+    /// <param name="role">Optional role to add as the first message. Defaults to <see cref="AuthorRole.System"/> role</param>
+    public ChatHistory(string systemMessage, AuthorRole? role = null)
```
Comment (SergeyMenshykh) [inline dotnet/src/SemanticKernel.Abstractions/AI/ChatCompletion/ChatHistory.cs:36]: If the role is not "system," then the `systemMessage` parameter does not contain a system message, as someone may think when looking at the parameter name. Consider renaming it to just `message`.

Comment (RogerBarreto) [reply dotnet/src/SemanticKernel.Abstractions/AI/ChatCompletion/ChatHistory.cs:36]: I thought about it, but didn't want to introduce this breaking change for named parameters, the other changes don't introduce code breaking changes. But I can reconsider.
