### PR TITLE
.Net: [MEVD] Fix Guid (and other) keys for dynamic collections

### LINKED ISSUE #13340: [MEVD] Guid (and other) key types not properly supported in dynamic mode
In the recent #13315, I added Guid support for all providers, as well as KeyTypeTests which ensure that all providers properly support all keys they claim they do. Unfortunately, I left out support for dynamic collections, which in certain providers use different mappers which must also be updated to support the key types.

/cc @adamsitnik

### PR DESCRIPTION
**Pull request by roji**
Closes #13340

### CODE REVIEW

File: dotnet/src/VectorData/AzureAISearch/AzureAISearchDynamicMapper.cs [hunk 1]
```diff
@@ -97,9 +99,16 @@ public JsonObject MapFromDataToStorageModel(Dictionary<string, object?> dataMode
             switch (property)
             {
                 case KeyPropertyModel keyProperty:
-                    result[keyProperty.ModelName] = (string?)storageModel[keyProperty.StorageName]
+                    var key = (string?)storageModel[keyProperty.StorageName]
```
Comment (adamsitnik) [inline dotnet/src/VectorData/AzureAISearch/AzureAISearchDynamicMapper.cs:102]: Just to make sure I understand: it always comes back as a string from the service, but we parse it to Guid on our own?

**Review by adamsitnik — APPROVED** [review]
LGTM, big thanks for such a quick fix @roji !
