### PR TITLE
.Net: Fix OpenAiResponseAgent chat message images removed by SK

### LINKED ISSUE #12888: Bug: OpenAiResponseAgent chat message images removed by SK
**Describe the bug**
It appears that SK currently removes any `ImageContent` in a user message before it's sent to OpenAI. The offending code seems to be [this `ToResponseItem` call](https://github.com/microsoft/semantic-kernel/blob/main/dotnet/src/Agents/OpenAI/Internal/ResponseThreadActions.cs#L42). The implementation of this method only retains the main chat string and ignores all items.

Pseudocode:
```cs
ChatMessageContent userMessage = new ChatMessageContent(AuthorRole.User, "describe the image");
userMessage.Items.Add(new ImageContent(imageUri));
await foreach (AgentResponseItem<ChatMessageContent> response in agent.InvokeAsync(userMessage))
{
 // ...
}
```

**Platform**
 - Language: C#
 - Source: NuGet package version 1.61.0
 - AI model: o3-pro

### PR DESCRIPTION
**Pull request by markwallace-microsoft**
### Motivation and Context

Closes #12888 

### Contribution Checklist

- [ ] The code builds clean without any errors or warnings
- [ ] The PR follows the [SK Contribution Guidelines](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md) and the [pre-submission formatting script](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md#development-scripts) raises no violations
- [ ] All unit tests pass, and I have added new tests where possible
- [ ] I didn't break anyone :smile:

### CODE REVIEW

File: dotnet/src/Agents/OpenAI/Extensions/KernelContentExtensions.cs [hunk 1]
```diff
@@ -0,0 +1,52 @@
...
+/// </summary>
+internal static class KernelContentExtensions
+{
+    internal static ResponseContentPart ToResponseContentPart(this KernelContent content)
+    {
+        return content switch
+        {
+            TextContent textContent => textContent.ToResponseContentPart(),
+            ImageContent imageContent => imageContent.ToResponseContentPart(),
+            BinaryContent binaryContent => binaryContent.ToResponseContentPart(),
```
Comment (rogerbarreto) [inline dotnet/src/Agents/OpenAI/Extensions/KernelContentExtensions.cs:19]: Since we are touching this implementation suggest considering adding the Audio type as well if supported by the responses SDK types.

One example how we do for the non-responses.
https://github.com/microsoft/semantic-kernel/blob/9568fe841381ef2bbe303de92fc0f8357d10791b/dotnet/src/Connectors/Connectors.OpenAI/Core/ClientCore.ChatCompletion.cs#L882

**Review by rogerbarreto — APPROVED** [review]

File: dotnet/src/Agents/OpenAI/Extensions/KernelContentExtensions.cs (hunk 1 above)
Comment (markwallace-microsoft) [reply dotnet/src/Agents/OpenAI/Extensions/KernelContentExtensions.cs:19]: The `BinaryContent` support handles the audio type
