### PR TITLE
.Net: Filter out reasoning response items during function calling

### LINKED ISSUE #12904: .Net: Bug: Reasoning messages not removed when using OpenAIResponseAgent with tools
**Describe the bug**
OpenAI models with reasoning capabilities will return reasoning messages in responses. `OpenAIResponseAgent` does not remove reasoning messages in subsequent API call after a tool call, causing an API error:

```
HTTP 400 (invalid_request_error: )
Parameter: input

Item with id 'rs_***' not found. Items are not persisted when `store` is set to false. Try again with `store` set to true, or remove this item from your input.
```

**To Reproduce**
1. Create `OpenAIResponseAgent` with a reasoning model (GPT-5, o4-mini, ...) and tools
2. Send a message to agent that triggers a tool call
3. See error

**Expected behavior**
Reasoning messages should be removed in subsequent API call after a tool call.

**Screenshots**
N/A

**Platform**
 - Language: C#
 - Source: NuGet Microsoft.SemanticKernel.Agents.OpenAI 1.61.0-preview
 - AI model: OpenAI:GPT-5
 - IDE: Visual Studio
 - OS: Windows

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by markwallace-microsoft**
### Motivation and Context

Closes #12904 

### Contribution Checklist

- [ ] The code builds clean without any errors or warnings
- [ ] The PR follows the [SK Contribution Guidelines](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md) and the [pre-submission formatting script](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md#development-scripts) raises no violations
- [ ] All unit tests pass, and I have added new tests where possible
- [ ] I didn't break anyone :smile:

### CODE REVIEW

File: dotnet/src/Agents/OpenAI/Internal/ResponseThreadActions.cs [hunk 1]
```diff
@@ -57,7 +57,10 @@ internal static async IAsyncEnumerable<ChatMessageContent> InvokeAsync(
             }
             else
             {
-                inputItems.AddRange(response.OutputItems);
+                var filteredItems = response.OutputItems
+                    .Where(item => item is not ReasoningResponseItem) // Keep items that are not ReasoningResponseItem  
+                    .ToList();
+                inputItems.AddRange(filteredItems);
```
Comment (dmytrostruk) [inline dotnet/src/Agents/OpenAI/Internal/ResponseThreadActions.cs]: nit: `ToList` can be removed, since `AddRange` accepts `IEnumerable`:
```suggestion
                    .Where(item => item is not ReasoningResponseItem); // Keep items that are not ReasoningResponseItem  
                inputItems.AddRange(filteredItems);
```
