### PR TITLE
.Net: [MEVD] Fix dynamic batching APIs for PostgreSQL

### LINKED ISSUE #13303: .Net: [MEVD] Batching GetAsync and DeleteAsync don't work in dynamic mode
We have a typing issue with the intersection of the batching APIs accepting keys (GetAsync, DeleteAsync) and dynamic collections. In a nutshell, with dynamic collections, the generic TKey type is `object`, and so GetAsync/DeleteAsync accept `IEnumerable<object>`. At the same time, the actual implementation of these methods in providers infers the (concrete) key type from the parameter type, but `object` obviously isn't a supported key type.

This is a provider implementation issue: we need to stop looking at the generic type.

```c#
using var collection = new PostgresDynamicCollection(
    "Host=localhost;Username=test;Password=test",
    "test",
    new()
    {
        Definition = new()
        {
            Properties =
            [
                new VectorStoreKeyProperty("Id", typeof(int)),
                new VectorStoreDataProperty("Text", typeof(string)),
                new VectorStoreVectorProperty("Embedding", typeof(float[]), dimensions: 3)
            ]
        }
    });

await collection.EnsureCollectionDeletedAsync();
await collection.EnsureCollectionExistsAsync();

// Unsupported key type Object
await collection.DeleteAsync(new object[] { 1, 2 });

// Resolves to non-batching DeleteAsync(object key), errors because array of ints isn't supported (or isn't the right key type)
await collection.DeleteAsync(new int[] { 1, 2 });

// Does not compile: cannot convert from 'int[]' to 'System.Collections.Generic.IEnumerable<object>'
await collection.DeleteAsync(keys: new int[] { 1, 2 });

// Same thing happens with GetAsync
_ = await collection.GetAsync(new object[] { 1, 2 }).ToArrayAsync();
_ = await collection.GetAsync(new int[] { 1, 2 });
_ = await collection.GetAsync(keys: new int[] { 1, 2 }).ToArrayAsync();
```

### PR DESCRIPTION
**Pull request by roji**
Fixes #13303

### CODE REVIEW

File: dotnet/src/VectorData/PgVector/PostgresSqlBuilder.cs [hunk 1]
```diff
@@ -269,7 +269,7 @@ internal static void BuildGetCommand<TKey>(NpgsqlCommand command, string schema,
     internal static void BuildGetBatchCommand<TKey>(NpgsqlCommand command, string schema, string tableName, CollectionModel model, List<TKey> keys, bool includeVectors = false)
         where TKey : notnull
     {
-        NpgsqlDbType? keyType = PostgresPropertyMapping.GetNpgsqlDbType(typeof(TKey)) ?? throw new ArgumentException($"Unsupported key type {typeof(TKey).Name}");
+        NpgsqlDbType? keyType = PostgresPropertyMapping.GetNpgsqlDbType(model.KeyProperty.Type) ?? throw new UnreachableException($"Unsupported key type {typeof(TKey).Name}");
```
Comment (westey-m) [inline dotnet/src/VectorData/PgVector/PostgresSqlBuilder.cs]: Should the messages also contain the key type from the model?
```suggestion
        NpgsqlDbType? keyType = PostgresPropertyMapping.GetNpgsqlDbType(model.KeyProperty.Type) ?? throw new UnreachableException($"Unsupported key type {model.KeyProperty.Type.Name}");
```

Comment (roji) [reply dotnet/src/VectorData/PgVector/PostgresSqlBuilder.cs]: Good catch, thanks.
