### PR TITLE
.Net: Add JsonConverter's to handle bool values when converting from PromptExecutionSettings

### LINKED ISSUE #11304: .Net: Bug: CreateFunctionFromPrompty does not deserialise boolean parameter values correctly
**Describe the bug**
Boolean model parameters are deserialised as string values. This causes an exception on calling `OpenAIPromptExecutionSettings.FromExecutionSettings`

**To Reproduce**
1. Create a dotnet console app
2. Add references to `Microsoft.SemanticKernel` 1.44.0, `Microsoft.SemanticKernel.Prompty` 1.44.0-alpha
3. Program.cs:
  ```csharp
using Microsoft.SemanticKernel;
using Microsoft.SemanticKernel.Connectors.OpenAI;

#pragma warning disable SKEXP0010, SKEXP0040 // Type is for evaluation purposes only and is subject to change or removal in future updates. Suppress this diagnostic to proceed.

var kernel = new Kernel();

var kernelFunction = kernel.CreateFunctionFromPrompty("""
    ---
    name: SomePrompt
    description: This is the description.
    model:
        api: chat
        configuration:
            type: azure_openai_beta
        parameters:
            logprobs: true
    ---
    Abc---def
    """);

PromptExecutionSettings settings = kernelFunction.ExecutionSettings!["default"];

Console.WriteLine(settings.ExtensionData!["logprobs"].GetType());   // shows System.String but should be System.Boolean

var executionSettings = OpenAIPromptExecutionSettings.FromExecutionSettings(settings);  // throws exception

Console.WriteLine(executionSettings.Logprobs);
  ```

**Expected behavior**
Program runs without exception and outputs correct value of `LogProbs` property.

**Actual behavior**
Throws exception

```
System.Text.Json.JsonException
  HResult=0x80131500
  Message=The JSON value could not be converted to System.Nullable`1[System.Boolean]. Path: $.logprobs | LineNumber: 0 | BytePositionInLine: 84.
  Source=System.Text.Json
  StackTrace:
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo`1 jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo`1 jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at Microsoft.SemanticKernel.Connectors.OpenAI.OpenAIPromptExecutionSettings.FromExecutionSettings(PromptExecutionSettings executionSettings, Nullable`1 defaultMaxTokens)
   at Program.<Main>$(String[] args) in C:\Users\Developer\source\repos\ConsoleApp4\Program.cs:line 26

  This exception was originally thrown at this call stack:
    System.Text.Json.ThrowHelper.ThrowInvalidOperationException_ExpectedBoolean(System.Text.Json.JsonTokenType)
    System.Text.Json.Utf8JsonReader.GetBoolean()
    System.Text.Json.Serialization.Converters.NullableConverter<T>.Read(ref System.Text.Json.Utf8JsonReader, System.Type, System.Text.Json.JsonSerializerOptions)
    System.Text.Json.Serialization.Metadata.JsonPropertyInfo<T>.ReadJsonAndSetMember(object, ref System.Text.Json.ReadStack, ref System.Text.Json.Utf8JsonReader)
    System.Text.Json.Serialization.Converters.ObjectDefaultConverter<T>.OnTryRead(ref System.Text.Json.Utf8JsonReader, System.Type, System.Text.Json.JsonSerializerOptions, ref System.Text.Json.ReadStack, out T)
    System.Text.Json.Serialization.JsonConverter<T>.TryRead(ref System.Text.Json.Utf8JsonReader, System.Type, System.Text.Json.JsonSerializerOptions, ref System.Text.Json.ReadStack, out T, out bool)
    System.Text.Json.Serialization.JsonConverter<T>.ReadCore(ref System.Text.Json.Utf8JsonReader, System.Text.Json.JsonSerializerOptions, ref System.Text.Json.ReadStack)

Inner Exception 1:
InvalidOperationException: Cannot get the value of a token type 'String' as a boolean.

```

### PR DESCRIPTION
**Pull request by markwallace-microsoft**
### Motivation and Context

Closes #11304 

### Contribution Checklist

- [ ] The code builds clean without any errors or warnings
- [ ] The PR follows the [SK Contribution Guidelines](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md) and the [pre-submission formatting script](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md#development-scripts) raises no violations
- [ ] All unit tests pass, and I have added new tests where possible
- [ ] I didn't break anyone :smile:

### CODE REVIEW

File: dotnet/src/InternalUtilities/src/Text/OptionalBoolJsonConverter.cs [hunk 1]
```diff
@@ -0,0 +1,65 @@
...
+/// Serializing a <see cref="PromptExecutionSettings"/> instance without this converter will throw a 'System.Text.Json.JsonException : The JSON value could not be converted to System.Nullable'
+/// if there are any bool properties.
+/// </summary>
+[ExcludeFromCodeCoverage]
+internal sealed class OptionalBoolJsonConverter : JsonConverter<bool?>
+{
+    /// <inheritdoc/>
+    public override bool? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
+    {
+        if (reader.TokenType == JsonTokenType.String)
```
Comment (RogerBarreto) [inline dotnet/src/InternalUtilities/src/Text/OptionalBoolJsonConverter.cs:23]:
```suggestion
        if (reader.TokenType == JsonTokenType.Null) { return null; }
        if (reader.TokenType == JsonTokenType.String)
```

File: dotnet/src/SemanticKernel.Abstractions/AI/PromptExecutionSettings.cs [hunk 2]
```diff
@@ -36,7 +35,6 @@ public class PromptExecutionSettings
     /// When provided, this service identifier will be the key in a dictionary collection of execution settings for both <see cref="KernelArguments"/> and <see cref="PromptTemplateConfig"/>.
     /// If not provided the service identifier will be the default value in <see cref="DefaultServiceId"/>.
     /// </remarks>
-    [Experimental("SKEXP0001")]
```
Comment (RogerBarreto) [inline dotnet/src/SemanticKernel.Abstractions/AI/PromptExecutionSettings.cs:39]: Are we graduating as part of this changes? Suggest having in a different PR.

File: dotnet/src/InternalUtilities/src/Text/OptionalBoolJsonConverter.cs [hunk 3]
```diff
@@ -0,0 +1,65 @@
...
+                return null;
+            }
+            if (value.Equals("true", StringComparison.OrdinalIgnoreCase))
+            {
+                return true;
+            }
+            else if (value.Equals("false", StringComparison.OrdinalIgnoreCase))
+            {
+                return false;
+            }
```
[the remark this answers is not in the document]
Comment (markwallace-microsoft) [reply dotnet/src/InternalUtilities/src/Text/OptionalBoolJsonConverter.cs:37]: TryParse will succeed for strings like "123" which we aren't valid. Also if the property is set to " true " then this shouldn't match either.

[the remark this answers is not in the document]
Comment (markwallace-microsoft) [reply dotnet/src/InternalUtilities/src/Text/OptionalBoolJsonConverter.cs:37]: Keeping things strict for now

File: dotnet/src/InternalUtilities/src/Text/OptionalBoolJsonConverter.cs [hunk 4]
```diff
@@ -0,0 +1,69 @@
+﻿// Copyright (c) Microsoft. All rights reserved.
```
Comment (SergeyMenshykh) [inline dotnet/src/InternalUtilities/src/Text/OptionalBoolJsonConverter.cs:1]: nit: it's possible to have one converter instead of two to handle both bool and bool?:
```csharp
internal sealed class BoolJsonConverter : JsonConverter<object>
{
    /// <inheritdoc/>
    public override bool CanConvert(Type typeToConvert)
    {
        return typeToConvert == typeof(bool) || typeToConvert == typeof(bool?);
    }
    ...
}
```

**Review by SergeyMenshykh — APPROVED** [review]

File: dotnet/src/Functions/Functions.Prompty/Functions.Prompty.csproj [hunk 5]
```diff
@@ -4,7 +4,7 @@
     <AssemblyName>Microsoft.SemanticKernel.Prompty</AssemblyName>
     <RootNamespace>$(AssemblyName)</RootNamespace>
     <TargetFrameworks>net8.0;netstandard2.0</TargetFrameworks>
-    <VersionSuffix>alpha</VersionSuffix>
+    <VersionSuffix>beta</VersionSuffix>
```
[the remark this answers is not in the document]
Comment (markwallace-microsoft) [reply dotnet/src/Functions/Functions.Prompty/Functions.Prompty.csproj:7]: Yes this is intentional

File: dotnet/src/InternalUtilities/src/Text/OptionalBoolJsonConverter.cs (hunk 4 above)
Comment (markwallace-microsoft) [reply dotnet/src/InternalUtilities/src/Text/OptionalBoolJsonConverter.cs:1]: I tried but I get this error

```
System.InvalidCastException : Unable to cast object of type 'Microsoft.SemanticKernel.Text.BoolJsonConverter' to type 'System.Text.Json.Serialization.JsonConverter`1[System.Nullable`1[System.Boolean]]'.
```

File: dotnet/src/InternalUtilities/src/Text/BoolJsonConverter.cs [hunk 6]
```diff
@@ -0,0 +1,58 @@
...
+            return false;
+        }
+
+        throw new ArgumentException($"Invalid token type found '{reader.TokenType}', expected a boolean value.");
+    }
+
+    /// <inheritdoc/>
+    public override void Write(Utf8JsonWriter writer, bool value, JsonSerializerOptions options)
+    {
+        writer.WriteBooleanValue((bool)value);
```
Comment (dmytrostruk) [inline dotnet/src/InternalUtilities/src/Text/BoolJsonConverter.cs:56]: nit: Do we need this conversion? It looks like `value` is already of type `bool`.

**Review by dmytrostruk — APPROVED** [review]

File: dotnet/src/InternalUtilities/src/Text/OptionalBoolJsonConverter.cs [hunk 7]
```diff
@@ -0,0 +1,69 @@
...
+    public override bool? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
+    {
+        if (reader.TokenType == JsonTokenType.String)
+        {
+            string? value = reader.GetString();
+            if (value is null)
+            {
+                return null;
+            }
+            if (value.Equals("true", StringComparison.OrdinalIgnoreCase))
```
Comment (crickman) [inline dotnet/src/InternalUtilities/src/Text/OptionalBoolJsonConverter.cs:30]: nit - `bool.TrueString`

File: dotnet/src/InternalUtilities/src/Text/OptionalBoolJsonConverter.cs [hunk 8]
```diff
@@ -0,0 +1,69 @@
...
+            {
+                return true;
+            }
+            else if (value.Equals("false", StringComparison.OrdinalIgnoreCase))
```
Comment (crickman) [inline dotnet/src/InternalUtilities/src/Text/OptionalBoolJsonConverter.cs:34]: nit - `bool.FalseString`

File: dotnet/src/InternalUtilities/src/Text/OptionalBoolJsonConverter.cs [hunk 9]
```diff
@@ -0,0 +1,69 @@
...
+    /// <inheritdoc/>
+    public override bool? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
+    {
+        if (reader.TokenType == JsonTokenType.String)
+        {
+            string? value = reader.GetString();
+            if (value is null)
+            {
+                return null;
+            }
```
Comment (crickman) [inline dotnet/src/InternalUtilities/src/Text/OptionalBoolJsonConverter.cs:29]: nit - Wouldn't `bool.TryParse` only evaluate `value` once (instead of twice?)

Comment (RogerBarreto) [reply dotnet/src/InternalUtilities/src/Text/OptionalBoolJsonConverter.cs:29]: This removes the strict "true" , "false" values, allowing " true ", "    false " strings to be valid, should we have the same to the non-nullable converter? May need to bring back the tests where string boolean values aren't trimmed.

**Review by RogerBarreto — APPROVED** [review]

File: dotnet/src/InternalUtilities/src/Text/OptionalBoolJsonConverter.cs (hunk 9 above)
Comment (markwallace-microsoft) [reply dotnet/src/InternalUtilities/src/Text/OptionalBoolJsonConverter.cs:29]: I have made the two implementations consistent

**Review by SergeyMenshykh — APPROVED** [review]

**Comment by markwallace-microsoft** [comment]
Following integration tests failed but this looks unrelated to the PR

```
[xUnit.net 00:00:00.69]     SemanticKernel.Connectors.AzureOpenAI.UnitTests.KernelCore.KernelTests.FunctionUsageMetricsAreCapturedByTelemetryAsExpected [FAIL]
[xUnit.net 00:00:00.69]       Assert.Contains() Failure: Item not found in collection
[xUnit.net 00:00:00.69]       Collection: [55]
[xUnit.net 00:00:00.69]       Not found:  12
```

**Comment by markwallace-microsoft** [comment]
Another unrelated test failure:
```
[xUnit.net 00:00:02.36]     SemanticKernel.Functions.UnitTests.OpenApi.Extensions.ApiManifestKernelExtensionsTests.ItCanCreatePluginFromApiManifestWithDescriptionParameterAsync [FAIL]
[xUnit.net 00:00:02.36]       Microsoft.SemanticKernel.HttpOperationException : An error occurred while sending the request.
[xUnit.net 00:00:02.36]       ---- System.Net.Http.HttpRequestException : An error occurred while sending the request.
[xUnit.net 00:00:02.36]       -------- System.IO.IOException : Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
[xUnit.net 00:00:02.36]       ------------ System.Net.Sockets.SocketException : An existing connection was forcibly closed by the remote host.
```
