### PR TITLE
.Net MEVD: Unify collection deletion and creation

### LINKED ISSUE #10882: .Net: Behavior of collection deletion
DeleteCollectionAsync seems to behave differently across store engines, when a collection doesn’t exist. 

In some cases no error (expected behavior), in other instances an exception “the collection doesn’t exist” is thrown.

### PR DESCRIPTION
**Pull request by adamsitnik**
fixes #10882

### CODE REVIEW

**Review by westey-m — APPROVED** [review]

File: dotnet/src/VectorDataIntegrationTests/QdrantIntegrationTests/Collections/QdrantCollectionConformanceTests.cs [hunk 1]
```diff
@@ -0,0 +1,12 @@
+﻿// Copyright (c) Microsoft. All rights reserved.
+
+using QdrantIntegrationTests.Support;
+using VectorDataSpecificationTests.Collections;
+using Xunit;
+
+namespace QdrantIntegrationTests.Collections;
+
+public class QdrantCollectionConformanceTests(QdrantFixture fixture)
```
[the remark this answers is not in the document]
Comment (adamsitnik) [reply dotnet/src/VectorDataIntegrationTests/QdrantIntegrationTests/Collections/QdrantCollectionConformanceTests.cs]: I was not aware of that. I addded it since it was an easy change and would be great to make sure the conformance tests cover all code paths.

**Review by westey-m — APPROVED** [review]

File: dotnet/src/Connectors/Connectors.Memory.InMemory/InMemoryVectorStoreRecordCollection.cs [hunk 2]
```diff
@@ -113,13 +113,19 @@ public Task<bool> CollectionExistsAsync(CancellationToken cancellationToken = de
     /// <inheritdoc />
     public Task CreateCollectionAsync(CancellationToken cancellationToken = default)
     {
-        if (!this._internalCollections.ContainsKey(this._collectionName))
+        if (!this._internalCollections.ContainsKey(this._collectionName)
```
Comment (roji) [inline dotnet/src/Connectors/Connectors.Memory.InMemory/InMemoryVectorStoreRecordCollection.cs:116]: Can remove the ContainsKey, given that TryAdd is being used below, no?

File: dotnet/src/Connectors/Connectors.Memory.Weaviate/WeaviateVectorStoreRecordCollection.cs [hunk 3]
```diff
@@ -535,5 +536,24 @@ private static void VerifyVectorParam<TVector>(TVector vector)
         }
     }
 
+    private static void VerifyCollectionName(string collectionName)
```
Comment (roji) [inline dotnet/src/Connectors/Connectors.Memory.Weaviate/WeaviateVectorStoreRecordCollection.cs:539]: Is there a good reason for us to perform client-side validation for this, i.e. isn't it better to just let the server fail? This would avoid us having to encode server restrictions in client code (these may change in the future), maintain the code etc.

One possible reason to do something like this is if the server errors in a totally cryptic way, i.e. returns an error that the user simply wouldn't understand - then we can add the client-side "service" of providing a good error to the user. But IIRC that wasn't the case here, so I'd propose removing.

File: dotnet/src/VectorDataIntegrationTests/SqliteIntegrationTests/Support/SqliteFixture.cs [hunk 4]
```diff
@@ -0,0 +1,10 @@
+﻿// Copyright (c) Microsoft. All rights reserved.
+
+using VectorDataSpecificationTests.Support;
+
+namespace SqliteIntegrationTests.Support;
+
+public class SqliteFixture : VectorStoreFixture
```
Comment (roji) [inline dotnet/src/VectorDataIntegrationTests/SqliteIntegrationTests/Support/SqliteFixture.cs:7]: Do you think these "generic" provider-specific fixtures improve things? The problem is that there's also VectorStoreCollectionFixture which directly extends VectorStoreFixture, so to follow this pattern you'd have to also have SqliteVectorStoreCollectionFixture which extends that and just overrides TestStore (because no multiple inheritance)...

At the end of the day I'm not sure it adds much value beyond each **concrete** fixture (SqliteBasicFilterTests.Fixture) overriding TestStore directly (as before this PR) - it's almost the same as inheriting SqliteVectorStoreCollectionFixture.

**Review by roji — APPROVED** [review]
Thanks @adamsitnik! See minor comments below.

File: dotnet/src/Connectors/Connectors.Memory.AzureCosmosDBMongoDB/AzureCosmosDBMongoDBVectorStoreRecordCollection.cs [hunk 5]
```diff
@@ -102,20 +102,29 @@ public virtual Task<bool> CollectionExistsAsync(CancellationToken cancellationTo
...
     {
-        if (!await this.CollectionExistsAsync(cancellationToken).ConfigureAwait(false))
-        {
-            await this.CreateCollectionAsync(cancellationToken).ConfigureAwait(false);
-        }
+        await this.RunOperationAsync("CreateCollection",
+            () => this._mongoDatabase.CreateCollectionAsync(this.CollectionName, cancellationToken: cancellationToken)).ConfigureAwait(false);
+
+        await this.RunOperationAsync("CreateIndexes",
+            () => this.CreateIndexesAsync(this.CollectionName, cancellationToken: cancellationToken)).ConfigureAwait(false);
```
[the remark this answers is not in the document]
Comment (adamsitnik) [reply dotnet/src/Connectors/Connectors.Memory.AzureCosmosDBMongoDB/AzureCosmosDBMongoDBVectorStoreRecordCollection.cs:127]: The `IMongoDatabase.CreateCollectionAsync` "Creates a new collection if not already available". Because of that, so far `CreateCollectionAsync` was acting like `CreateCollectionIfNotExistsAsync` (no failing when it already exists). So I've literally moved `CreateCollectionAsync` code to `CreateCollectionIfNotExistsAsync`.

File: dotnet/src/Connectors/Connectors.Memory.InMemory/InMemoryVectorStoreRecordCollection.cs (hunk 2 above)
Comment (adamsitnik) [reply dotnet/src/Connectors/Connectors.Memory.InMemory/InMemoryVectorStoreRecordCollection.cs:116]: Yes, but then we would be always allocating a dictionary first.

File: dotnet/src/Connectors/Connectors.Memory.Weaviate/WeaviateVectorStoreRecordCollection.cs (hunk 3 above)
Comment (adamsitnik) [reply dotnet/src/Connectors/Connectors.Memory.Weaviate/WeaviateVectorStoreRecordCollection.cs:539]: When we provide lowercase name to `Weaviate`, it's going to perform the upper-casing of the first letter and create a collection with such name. And from this moment, it's going to expect us to always use the modified name for all operations. 

Some pseudocode to demonstrate it:

```cs
var collection = new WeaviateCollection("test");
await collection.CreateCollectionIfNotExistsAsync(); // creates "Test" collection
Console.WriteLine(await collection.CollectionExistsAsync()); // prints "False" because "test" does not exist

collection = new WeaviateCollection("Test");
Console.WriteLine(await collection.CollectionExistsAsync());  // prints "True" because "Test" does exist
```

Comment (roji) [reply dotnet/src/Connectors/Connectors.Memory.Weaviate/WeaviateVectorStoreRecordCollection.cs:539]: OK makes sense, good improvement!

File: dotnet/src/VectorDataIntegrationTests/SqliteIntegrationTests/Support/SqliteFixture.cs (hunk 4 above)
Comment (roji) [reply dotnet/src/VectorDataIntegrationTests/SqliteIntegrationTests/Support/SqliteFixture.cs:7]: OK, no big deal either way.

**Comment by roji** [comment]
Thoughts about merging this to the feature branch vs. main? This does change behavior so maybe better to wait with it...

File: dotnet/src/IntegrationTests/Connectors/Memory/Weaviate/WeaviateVectorStoreTests.cs [hunk 6]
```diff
@@ -9,4 +10,7 @@ namespace SemanticKernel.IntegrationTests.Connectors.Memory.Weaviate;
 [Collection("WeaviateVectorStoreCollection")]
 public sealed class WeaviateVectorStoreTests(WeaviateVectorStoreFixture fixture)
     : BaseVectorStoreTests<Guid, WeaviateHotel>(new WeaviateVectorStore(fixture.HttpClient!))
-{ }
+{
+    // Weaviate requires each collection name to start with upercase ASCII letter.
```
Comment (adamsitnik) [inline dotnet/src/IntegrationTests/Connectors/Memory/Weaviate/WeaviateVectorStoreTests.cs:14]:
```suggestion
    // Weaviate requires each collection name to start with uppercase ASCII letter.
```

**Review by westey-m — APPROVED** [review]

**Review by roji — APPROVED** [review]
