### PR TITLE
.Net: Fixes MCP Behavior for AIFunction.AsKernelFunction() + Fix ensuring FunctionChoiceBehavior works correctly with IChatClients.

### LINKED ISSUE #12209: .Net: Bug: FunctionChoiceBehavior.None() does not prevent function call with AddAzureOpenAIChatClient
## Description
**Describe the bug**
When specifying `FunctionChoiceBehavior.None()`, functions should not be called. However, when using `AddAzureOpenAIChatClient`, the function is still invoked. This issue does not occur when using `AddAzureOpenAIChatCompletion`, where the function is not called as expected. This only happens with `AddAzureOpenAIChatClient`.

**To Reproduce**
1. Create a new Console App project.
2. Add the following NuGet packages to your project:
   - Azure.Identity
   - Microsoft.SemanticKernel
3. Run the following code snippet:

```csharp
using Azure.Identity;
using Microsoft.SemanticKernel;
using System.ComponentModel;

var builder = Kernel.CreateBuilder();
builder.AddAzureOpenAIChatClient(
    "<<Your model deployment name>>",
    "https://<<Your AOAI resource name>>.openai.azure.com/",
    new AzureCliCredential());

builder.Plugins.AddFromType<TimePlugin>();

var kernel = builder.Build();

var result = await kernel.InvokePromptAsync("What is the current date and time?",
    arguments:new(new PromptExecutionSettings
    {
        FunctionChoiceBehavior = FunctionChoiceBehavior.None(),
    }));
Console.WriteLine(result.GetValue<string>());

public class TimePlugin
{
    [KernelFunction, Description("Returns the current local date and time as a formatted string (yyyy/MM/dd HH:mm:ss).")]
    public string GetCurrentDateTime() => 
        TimeProvider.System.GetLocalNow().ToString("yyyy/MM/dd HH:mm:ss");
}
```

4. AI answers the prompt and calls the function, returning the current date and time like this:
```
The current date and time is 2025/05/21 13:35:05.
```

**Expected behavior**
The function should not be called, and the AI should respond based only on its own knowledge, without using any registered functions.

**Platform**
 - Language: C#
 - Source: Microsoft.SemanticKernel v1.53.0
 - AI model: gpt-4.1
 - IDE: Visual Studio 2022
 - OS: Windows

**Additional context**
N/A

### LINKED ISSUE #12217: Bug: MCP tool integration is broken in 1.53.0
**Describe the bug**

```fsharp
kernel.Plugins.AddFromFunctions("CurrentDateTool", tools |> Seq.map _.AsKernelFunction()) |> ignore
```

Importing plugin from kernel function occurs with prefixed name "plugin_function", while later function is retrieved using just "function" name, so integration is broken later.

Issue is not reproduced in 1.52.0

**To Reproduce**
Check out the repro, change SemanticKernel version to 1.53.0
https://github.com/Lanayx/Oxpecker/tree/develop/examples/MCP

**Expected behavior**
MCP function is added as plugin properly and can be used later

**Screenshots**

Image

**Platform**
 - Language: [F#]
 - Source: [NuGet package version 1.53.0]
 - AI model: [Ollama + Llama3.2]
 - IDE: [Rider]
 - OS: [Windows]

### PR DESCRIPTION
**Pull request by RogerBarreto**
### Motivation and Context

- Fixes #12209
- Fixes #12217

### CODE REVIEW

File: dotnet/src/SemanticKernel.Abstractions/AI/PromptExecutionSettingsExtensions.cs [hunk 1]
```diff
@@ -146,7 +150,27 @@ public static class PromptExecutionSettingsExtensions
...
-            options.ToolMode = settings.FunctionChoiceBehavior is RequiredFunctionChoiceBehavior ? ChatToolMode.RequireAny : ChatToolMode.Auto;
+            if (settings.FunctionChoiceBehavior is AutoFunctionChoiceBehavior autoChoiceBehavior)
+            {
+                options.ToolMode = ChatToolMode.Auto;
+                options.AllowMultipleToolCalls = autoChoiceBehavior.Options?.AllowParallelCalls;
+            }
+            else
+            if (settings.FunctionChoiceBehavior is NoneFunctionChoiceBehavior noneFunctionChoiceBehavior)
+            {
+                // If the function choice behavior is None, we don't need to set the tools.
```
Comment (SergeyMenshykh) [inline dotnet/src/SemanticKernel.Abstractions/AI/PromptExecutionSettingsExtensions.cs:161]: This comment can be a little bit misleading because this behavior may require tools as well as other behaviors. The only difference is that this behavior instructs the model not to call tools, but the model may still use them for other reasons, such as dry runs: https://github.com/microsoft/semantic-kernel/blob/7243188e92d61d9eb9ef38a53060e6c2f4270e51/dotnet/src/SemanticKernel.Abstractions/AI/FunctionChoiceBehaviors/NoneFunctionChoiceBehavior.cs#L11

The tools are supplied for this and other behaviors after the last `else` block, so nothing needs to be done. Just pointing out that the comment may be misleading.

**Review by SergeyMenshykh — APPROVED** [review]

File: dotnet/src/SemanticKernel.Abstractions/AI/PromptExecutionSettingsExtensions.cs (hunk 1 above)
Comment (RogerBarreto) [reply dotnet/src/SemanticKernel.Abstractions/AI/PromptExecutionSettingsExtensions.cs]: I agree, comments aren't necessary as all those properties actually clarify what's doing.

File: dotnet/src/SemanticKernel.Abstractions/AI/ChatClient/KernelFunctionInvokingChatClient.cs [hunk 2]
```diff
@@ -111,4 +111,34 @@ await autoFunctionInvocationFilters[index].OnAutoFunctionInvocationAsync(
...
+
+        return base.GetResponseAsync(messages, options, cancellationToken);
+    }
+
+    public override IAsyncEnumerable<ChatResponseUpdate> GetStreamingResponseAsync(IEnumerable<ChatMessage> messages, ChatOptions? options = null, CancellationToken cancellationToken = default)
+    {
+        // If the autoInvoke is false, we don't call any function, just process the messages as is.
+        if (options is KernelChatOptions kernelChatOptions && (
+                kernelChatOptions.ExecutionSettings?.FunctionChoiceBehavior is AutoFunctionChoiceBehavior autoFunctionChoiceBehavior && !autoFunctionChoiceBehavior.AutoInvoke
+                || kernelChatOptions.ExecutionSettings?.FunctionChoiceBehavior is RequiredFunctionChoiceBehavior requiredFunctionChoiceBehavior && !requiredFunctionChoiceBehavior.AutoInvoke
```
Comment (markwallace-microsoft) [inline dotnet/src/SemanticKernel.Abstractions/AI/ChatClient/KernelFunctionInvokingChatClient.cs:135]: Not for this PR but it would be nice to create a utility function for this check, it looks the same as the code above

File: dotnet/src/SemanticKernel.Abstractions/AI/PromptExecutionSettingsExtensions.cs [hunk 3]
```diff
@@ -146,7 +150,23 @@ public static class PromptExecutionSettingsExtensions
...
         if (settings.FunctionChoiceBehavior?.GetConfiguration(new([]) { Kernel = kernel }).Functions is { Count: > 0 } functions)
         {
-            options.ToolMode = settings.FunctionChoiceBehavior is RequiredFunctionChoiceBehavior ? ChatToolMode.RequireAny : ChatToolMode.Auto;
+            if (settings.FunctionChoiceBehavior is AutoFunctionChoiceBehavior autoChoiceBehavior)
+            {
+                options.ToolMode = ChatToolMode.Auto;
+                options.AllowMultipleToolCalls = autoChoiceBehavior.Options?.AllowParallelCalls;
+            }
+            else
+            if (settings.FunctionChoiceBehavior is NoneFunctionChoiceBehavior noneFunctionChoiceBehavior)
```
Comment (markwallace-microsoft) [inline dotnet/src/SemanticKernel.Abstractions/AI/PromptExecutionSettingsExtensions.cs:159]: Do we need `noneFunctionChoiceBehavior`

File: dotnet/src/SemanticKernel.UnitTests/AI/ChatCompletion/AIFunctionKernelFunctionTests.cs [hunk 4]
```diff
@@ -55,7 +73,7 @@ public void ShouldUseKernelFunctionPluginAndNameWhenWrappingKernelFunction()
 
         // Assert
         Assert.Equal("TestPlugin_TestFunction", sut.Name);
-        Assert.Equal("TestPlugin", sut.PluginName);
+        Assert.Null(sut.PluginName);
```
Comment (markwallace-microsoft) [inline dotnet/src/SemanticKernel.UnitTests/AI/ChatCompletion/AIFunctionKernelFunctionTests.cs:76]: Why do we no longer know the plugin name?

Comment (RogerBarreto) [reply dotnet/src/SemanticKernel.UnitTests/AI/ChatCompletion/AIFunctionKernelFunctionTests.cs:76]: Actually, originally this instance was always created with a plug-in name provided, made it more flexible this time for helpers up in the stack.
