### PR TITLE
.Net: Create KernelPlugin from Open API without Kernel instance

### LINKED ISSUE #6426: .Net: Create Kernel Plugin from Open API spec doesn't support DI approach
To create Kernel Plugin from open AI spec, that can be registered in the kernel I need to use the none static **kernel.CreatePluginFromOpenAIAsync(pluginName, pluginUri)** function.
This function uses the kernel **instance** just to create logger.
I was wondering if it was implemented like that (dependent on a kernel instance) before you switched to the dependency injection approach?
Because injecting the kernel plugins to the DI container and then extract them in the kernel ctor will not work with this kind of plugins since the kernel itself is needed to create the plugin.

My ask is to have public static method that creates kernel plugin from plugin url (and plugin name) without the need for a kernel instance.

**Platform**
OS: Windows
IDE: Visual Studio,
Language: C#
Source: SK NuGet package version 1.10.0

### PR DESCRIPTION
**Pull request by markwallace-microsoft**
### Motivation and Context

Closes #6426 

### Contribution Checklist

- [ ] The code builds clean without any errors or warnings
- [ ] The PR follows the [SK Contribution Guidelines](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md) and the [pre-submission formatting script](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md#development-scripts) raises no violations
- [ ] All unit tests pass, and I have added new tests where possible
- [ ] I didn't break anyone :smile:

### CODE REVIEW

File: dotnet/samples/Concepts/Plugins/CreatePluginFromOpenApiSpec_RepairService.cs [hunk 1]
```diff
@@ -0,0 +1,83 @@
...
+using System.Text.Json.Serialization;
+using Microsoft.SemanticKernel;
+using Microsoft.SemanticKernel.Plugins.OpenApi;
+
+namespace Plugins;
+
+/// <summary>
+/// Sample shows how to create a <see cref="KernelPlugin"/> from an Open API manifest.
+/// </summary>
+public sealed class CreatePluginFromOpenApiSpec_RepairService(ITestOutputHelper output) : BaseTest(output)
```
Comment (westey-m) [inline dotnet/samples/Concepts/Plugins/CreatePluginFromOpenApiSpec_RepairService.cs:13]: Remember to update the README to add a link to this one.

File: dotnet/samples/Concepts/Plugins/CreatePluginFromOpenApiSpec_RepairService.cs [hunk 2]
```diff
@@ -0,0 +1,83 @@
...
+    private sealed class Repair
+    {
+        [JsonPropertyName("id")]
+        public int? Id { get; set; }
+
+        [JsonPropertyName("title")]
+        public string? Title { get; set; }
+
+        [JsonPropertyName("description")]
+        public string? description { get; set; }
```
Comment (SergeyMenshykh) [inline dotnet/samples/Concepts/Plugins/CreatePluginFromOpenApiSpec_RepairService.cs:72]: nit: Use Pascal case for this and the `assignedTo` property.

File: dotnet/src/Functions/Functions.OpenApi/OpenApiKernelPluginFactory.cs [hunk 3]
```diff
@@ -0,0 +1,344 @@
...
+
+namespace Microsoft.SemanticKernel.Plugins.OpenApi;
+
+/// <summary>
+/// Provides static factory methods for creating OpenAPI KernelPlugin implementations.
+/// </summary>
+public static partial class OpenApiKernelPluginFactory
+{
+    /// <summary>
+    /// Creates a plugin from an OpenAPI v3 endpoint.
```
Comment (SergeyMenshykh) [inline dotnet/src/Functions/Functions.OpenApi/OpenApiKernelPluginFactory.cs:25]: I think the summary of this method and the other ones should be rephrased not say anything about spec version and endpoint.

**Review by SergeyMenshykh — APPROVED** [review]

**Review by westey-m — APPROVED** [review]

**Review by SergeyMenshykh — APPROVED** [review]

**Review by SergeyMenshykh — APPROVED** [review]
