### PR TITLE
.Net: Allow Kernel to be mutable by AgentChatCompletions

### LINKED ISSUE #12534: .Net: Bug: Kernel.Data no longer retains information across plugins since v1.54
**Describe the bug**
Starting from version 1.54.0 of Semantic Kernel for C#, it appears there is a regression related to the Kernel.Data property.
Up to version 1.53.1, it was possible to:
- Populate Kernel.Data before and using inside a plugin.
- Add Kernel.Data inside a plugin and using in subsequent steps.

Since version 1.54.0, any key-value pairs added inside a plugin are no longer available afterward. 

> Note: The Kernel instance is registered in API solution as a KeyedScoped service using dependency injection.

**To Reproduce**
- Register the Kernel as a KeyedScoped service.
- Register plugin with Plugins.AddFromObject.
- InvokeStreaming of ChatCompletionAgent with a query that trigger the plugin.
- Within a plugin add new data to Kernel.Data.
- After execution, attempt to access the data added.
- Observe that the new data is missing: only key/value pair added before invoke are present.

**Expected behavior**
Kernel.Data should work as a shared state across the execution pipeline.
Any data added or modified in one plugin should persist and be accessible by later steps or plugins within the same scoped instance.

Behavior was confirmed to work correctly up to v1.53.1. The issue started appearing after upgrading to v1.54.0.

**Platform**
 - Language: C# (NET8)
 - Source: NuGet package version 1.54.0
 - AI model: Azure OpenAI:GPT-4o-mini(2024-07-18)
 - IDE: Visual Studio 2022
 - OS: Windows

**Additional context**
Information stored in Kernel.Data, such as retrieved document chunks, can be used after response generation to improve the quality and relevance of the knowledge stored in a vector database.

For example:
- Some documents are retrieved based on a user query (plugin input).
- documents are passed across kernel to be persisted with LLM generated response (Kernel Data).
- documents used in the generation of the response (plugin output).
- persist assistant response and retrieved document after InvokeStreaming generation

After response generation, both the original query and the model response are used to evaluate and refine the chunking and indexing strategy, improving future retrievals.

### PR DESCRIPTION
**Pull request by rogerbarreto**
### Motivation and Context

- Fixes #12534 

- This regression seems to be part of #11689 where `kernel` instance was is cloned prior agent iterations, as I didn't captured any failing unit tests for the added `AIContext` providers considering this as a valid fix.

- Added UT covering the expected `Kernel` mutability.

### CODE REVIEW

**Review by markwallace-microsoft — APPROVED** [review]

**Review by dmytrostruk — APPROVED** [review]

**Review by shethaadit — APPROVED** [review]

**Comment by markwallace-microsoft** [comment]
@RogerBarreto is this integration test failure related to your changes?

```
[xUnit.net 00:05:48.23]     SemanticKernel.IntegrationTests.Connectors.AzureOpenAI.AzureOpenAIChatClientRequiredFunctionChoiceBehaviorTests.SpecifiedInPromptInstructsConnectorToInvokeKernelFunctionAutomaticallyAsync [FAIL]
[xUnit.net 00:05:48.23]       Polly.Timeout.TimeoutRejectedException : The operation didn't complete within the allowed timeout of '00:00:30'.
[xUnit.net 00:05:48.23]       ---- System.Threading.Tasks.TaskCanceledException : The operation was canceled.
[xUnit.net 00:05:48.23]       -------- System.IO.IOException : Unable to read data from the transport connection: Operation canceled.
[xUnit.net 00:05:48.23]       ------------ System.Net.Sockets.SocketException : Operation canceled
```

File: dotnet/src/Agents/Core/ChatCompletionAgent.cs [hunk 1]
```diff
@@ -73,7 +73,7 @@ public override async IAsyncEnumerable<AgentResponseItem<ChatMessageContent>> In
             () => new ChatHistoryAgentThread(),
             cancellationToken).ConfigureAwait(false);
 
-        Kernel kernel = (options?.Kernel ?? this.Kernel).Clone();
+        Kernel kernel = options?.Kernel ?? this.Kernel;
```
Comment (westey-m) [inline dotnet/src/Agents/Core/ChatCompletionAgent.cs]: This change will result in a regression elsewhere, since it means that AIContextProviders will permanently mutate the kernel plugin list, and this mutation is expected to be per iteration only.
Let's discuss this further in the standup before committing.

Comment (rogerbarreto) [reply dotnet/src/Agents/Core/ChatCompletionAgent.cs]: > Let's discuss this further in the standup before committing.

Agree, actually the `AIContext` feature introduced this regression. I'm happy suggesting an alternative path for impacted customers using `Agents` with "Kernel data based functions".

**Comment by rogerbarreto** [comment]
@markwallace-microsoft This is unrelated error, I tried to run against my local configuration in Azure IT tests and passed as expected.

image

File: dotnet/src/Agents/Core/ChatCompletionAgent.cs (hunk 1 above)
Comment (rogerbarreto) [reply dotnet/src/Agents/Core/ChatCompletionAgent.cs]: After a review of the problem we agreed upon using a `Setting` for `Immutable` vs `Mutable` kernel approach for `Agents`, defaulting to the original behavior to avoid legacy / breaking-changes related to the new AIContext feature.

File: dotnet/src/Agents/Abstractions/Agent.cs [hunk 2]
```diff
@@ -66,6 +66,15 @@ public abstract class Agent
     /// </value>
     public Kernel Kernel { get; init; } = new();
 
+    /// <summary>
+    /// This option avoids the agent to mutate the original kernel instance during invocation. Default is <c>false</c>.
+    /// </summary>
+    /// <remarks>
+    /// Mutable kernels are currently not supported with <see cref="AIContextProvider"/> feature.
+    /// </remarks>
```
Comment (westey-m) [inline dotnet/src/Agents/Abstractions/Agent.cs]:
```suggestion
    /// <summary>
    /// This option forces the agent to clone the original kernel instance during invocation if <c>true</c>. Default is <c>false</c>.
    /// </summary>
    /// <remarks>
    /// <see cref="AIContextProvider"/> implementations that provide <see cref="AIFunction"/> instances require the
    /// kernel to be cloned during agent invocation, but cloning has the side affect of causing modifications to Kernel 
    /// Data by plugins to be lost.  Cloning is therefore opt-in.
    /// </remarks>
```

File: dotnet/src/Agents/Abstractions/Agent.cs [hunk 3]
```diff
@@ -66,6 +66,15 @@ public abstract class Agent
...
+    [Experimental("SKEXP0130")]
+    public bool UseImmutableKernel { get; set; } = false;
```
Comment (westey-m) [inline dotnet/src/Agents/Abstractions/Agent.cs:79]: Also consider AllowKernelCloning as the property name.

Comment (rogerbarreto) [reply dotnet/src/Agents/Abstractions/Agent.cs:79]: `Cloning` is our black box internal approach to make Kernel immutable, not sure if this sends a clearer message about what is the expected behavior of the `Kernel` provided.

I prefer `UseImmutableKernel` because is more clear on this perspective.

**Review by westey-m — APPROVED** [review]

**Review by markwallace-microsoft — APPROVED** [review]

**Comment by rogerbarreto** [comment]
@microsoft-github-policy-service agree company="Microsoft"
