### PR TITLE
.Net: Simplify example 52 to showcase using a custom OpenAIClient in genera…

### LINKED ISSUE #3844: .Net: Example52_ApimAuth -- Failed - Needs more comments
**Describe the bug**
> A clear and concise description of what the bug is.

1. Needs comments on what the point of this Example is showcasing, i.e., summary comment before the class definition
1. Link is broken, should be `https://learn.microsoft.com/en-us/semantic-kernel/deploy/use-ai-apis-with-api-management`
image

**Platform**
 - OS: Windows
 - IDE: VS Code Terminal
 - Language: C#
 - Source: V1 Release Candidate Bug Bash

### PR DESCRIPTION
**Pull request by glahaye**
…l instead of using one specifically for APIM

### Motivation and Context
Setting up APIM and AAD is tedious and is not directly related to what we want to showcase: that we can customize OpenAIClient instances used with SK.

resolves #3844 

### Description
Simplify examples and its requirements.

### Contribution Checklist
- [ ] The code builds clean without any errors or warnings
- [ ] The PR follows the [SK Contribution Guidelines](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md) and the [pre-submission formatting script](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md#development-scripts) raises no violations
- [ ] All unit tests pass, and I have added new tests where possible
- [ ] I didn't break anyone :smile:

### CODE REVIEW

File: dotnet/samples/KernelSyntaxExamples/Example52_CustomOpenAIClient.cs [hunk 1]
```diff
@@ -0,0 +1,58 @@
...
+
+        if (endpoint is null || deploymentName is null || apiKey is null)
+        {
+            Console.WriteLine("Azure OpenAI credentials not found. Skipping example.");
+            return;
+        }
+
+        // Create an HttpClient and include your custom header(s)
+        var httpClient = new HttpClient();
+        httpClient.DefaultRequestHeaders.Add("x-my-custom-hHeader", "My custom value");
```
Comment (SergeyMenshykh) [inline dotnet/samples/KernelSyntaxExamples/Example52_CustomOpenAIClient.cs:31]: nit: double **h** in the header name.

**Review by SergeyMenshykh — APPROVED** [review]

**Comment by SergeyMenshykh** [comment]
@markwallace-microsoft please check whether we need the APIM example or not. If I remember correctly, you had set up APIM to hide authentication details when crafting and executing prompts in VSCode extension.

**Review by markwallace-microsoft — APPROVED** [review]

**Review by SergeyMenshykh — APPROVED** [review]
