### PR TITLE
.Net: Fix MistralAI function calling and add image content support

### LINKED ISSUE #9806: .Net: New Feature: MistralAI - Multi-Modal Chatcompletion Support
---
name: MistralAI - Multi-Modal Chatcompletion Support
about: Add support for multimodal chat completion for the MistralAI connector.

---

Hey there,

i played a bit with the .Net Connector for MistralAI and noticed that the connector does not support multi modal chat completion.
It would be nice to have this be supported by the connector.

Best regards

### PR DESCRIPTION
**Pull request by markwallace-microsoft**
### Motivation and Context

Tool messages were being rejected as bad requests

Close #9806 

### Contribution Checklist

- [ ] The code builds clean without any errors or warnings
- [ ] The PR follows the [SK Contribution Guidelines](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md) and the [pre-submission formatting script](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md#development-scripts) raises no violations
- [ ] All unit tests pass, and I have added new tests where possible
- [ ] I didn't break anyone :smile:

### CODE REVIEW

File: dotnet/src/Connectors/Connectors.MistralAI/Client/ContentChunkType.cs [hunk 1]
```diff
@@ -0,0 +1,62 @@
...
+
+    /// <summary>
+    /// Returns a value indicating whether two <see cref="ContentChunkType"/> instances are not equivalent, as determined by a
+    /// case-insensitive comparison of their labels.
+    /// </summary>
+    /// <param name="left"> the first <see cref="ContentChunkType"/> instance to compare </param>
+    /// <param name="right"> the second <see cref="ContentChunkType"/> instance to compare </param>
+    /// <returns> false if left and right are both null or have equivalent labels; true otherwise </returns>
+    public static bool operator !=(ContentChunkType left, ContentChunkType right)
+        => !(left == right);
```
Comment (westey-m) [inline dotnet/src/Connectors/Connectors.MistralAI/Client/ContentChunkType.cs:46]: Shouldn't this be using `Equals` so that it compares .Type instead of the object intances?

File: dotnet/src/Connectors/Connectors.MistralAI/Client/ContentChunkType.cs [hunk 2]
```diff
@@ -0,0 +1,62 @@
...
+
+    /// <inheritdoc/>
+    public override bool Equals([NotNullWhen(true)] object? obj)
+        => obj is ContentChunkType otherRole && this == otherRole;
```
Comment (westey-m) [inline dotnet/src/Connectors/Connectors.MistralAI/Client/ContentChunkType.cs:50]: shouldn't `this == otherRole` also be using `.Type`?

**Review by westey-m — APPROVED** [review]

**Review by SergeyMenshykh — APPROVED** [review]

File: dotnet/src/Connectors/Connectors.MistralAI.UnitTests/Client/MistralClientTests.cs [hunk 3]
```diff
@@ -504,6 +522,31 @@ public void ValidateToMistralChatMessages(string roleLabel, string content)
         Assert.Single(messages);
     }
 
+    [Fact]
+    public void ValidateToMistralChatMessagesWithMultipleContents()
+    {
+        // Arrange
+        using var httpClient = new HttpClient();
```
Comment (RogerBarreto) [inline dotnet/src/Connectors/Connectors.MistralAI.UnitTests/Client/MistralClientTests.cs:529]: Is `httpclient` really necessary to create a MistralClient here, I see no usage of it.
```suggestion
```

File: dotnet/src/Connectors/Connectors.MistralAI/Client/ContentChunk.cs [hunk 4]
```diff
@@ -0,0 +1,13 @@
+﻿// Copyright (c) Microsoft. All rights reserved.
+
+using System.Text.Json.Serialization;
+
+namespace Microsoft.SemanticKernel.Connectors.MistralAI.Client;
+
+[JsonDerivedType(typeof(TextChunk))]
+[JsonDerivedType(typeof(ImageUrlChunk))]
+internal abstract class ContentChunk(ContentChunkType type)
```
Comment (RogerBarreto) [inline dotnet/src/Connectors/Connectors.MistralAI/Client/ContentChunk.cs:9]: Not sure why we need specific types for the chunks, cant we just use the Content chunk with both properties for now (that would simplify the code base, not sure if we need this specialization just for one field at each type.

```suggestion
internal abstract class ContentChunk(ContentChunkType type)
```

File: dotnet/src/Connectors/Connectors.MistralAI/Client/ContentChunkType.cs [hunk 5]
```diff
@@ -0,0 +1,62 @@
...
+
+using System;
+using System.Diagnostics.CodeAnalysis;
+using System.Text.Json.Serialization;
+
+namespace Microsoft.SemanticKernel.Connectors.MistralAI.Client;
+
+internal readonly struct ContentChunkType : IEquatable<ContentChunkType>
+{
+    public static ContentChunkType Text { get; } = new("text");
```
Comment (RogerBarreto) [inline dotnet/src/Connectors/Connectors.MistralAI/Client/ContentChunkType.cs:11]: If you opt in continue with the specific types, suggest moving them to `internal`s

```suggestion
    internal static ContentChunkType Text { get; } = new("text");
```

File: dotnet/src/Connectors/Connectors.MistralAI/MistralAIPromptExecutionSettings.cs [hunk 6]
```diff
@@ -180,6 +264,10 @@ public override PromptExecutionSettings Clone()
             RandomSeed = this.RandomSeed,
             ApiVersion = this.ApiVersion,
             ToolCallBehavior = this.ToolCallBehavior,
+            ResponseFormat = this.ResponseFormat,
+            FrequencyPenalty = this.FrequencyPenalty,
+            PresencePenalty = this.PresencePenalty,
+            Stop = this.Stop,
```
Comment (RogerBarreto) [inline dotnet/src/Connectors/Connectors.MistralAI/MistralAIPromptExecutionSettings.cs:270]: Missing create a ReadOnlyList from the editable list.

See here:
https://github.com/microsoft/semantic-kernel/blob/d9fd8ff5ba12c8047ca582fcd17f85bbe1978357/dotnet/src/Connectors/Connectors.OpenAI/Settings/OpenAIPromptExecutionSettings.cs#L304

Probably would add UnitTest to ensure its frozen for new parameters.

See here:
https://github.com/microsoft/semantic-kernel/blob/d9fd8ff5ba12c8047ca582fcd17f85bbe1978357/dotnet/src/Connectors/Connectors.OpenAI.UnitTests/Settings/OpenAIPromptExecutionSettingsTests.cs#L211

```suggestion
            Stop = this.Stop,
```

File: dotnet/src/Connectors/Connectors.MistralAI.UnitTests/Client/MistralClientTests.cs (hunk 3 above)
Comment (markwallace-microsoft) [reply dotnet/src/Connectors/Connectors.MistralAI.UnitTests/Client/MistralClientTests.cs:529]: It's used on the next line. Too much sunshine ;-)

File: dotnet/src/Connectors/Connectors.MistralAI/MistralAIPromptExecutionSettings.cs (hunk 6 above)
Comment (markwallace-microsoft) [reply dotnet/src/Connectors/Connectors.MistralAI/MistralAIPromptExecutionSettings.cs]: Added new unit tests and adopted the sample pattern as OpenAI

File: dotnet/src/Connectors/Connectors.MistralAI.UnitTests/Client/MistralClientTests.cs (hunk 3 above)
Comment (RogerBarreto) [reply dotnet/src/Connectors/Connectors.MistralAI.UnitTests/Client/MistralClientTests.cs:529]: I saw that, is that the httpClient is being created without any handler, for that reason, I don't think it is needed, unless the handler was used to inject testing behavior.

File: dotnet/src/Connectors/Connectors.MistralAI/Client/ContentChunkType.cs (hunk 2 above)
Comment (markwallace-microsoft) [reply dotnet/src/Connectors/Connectors.MistralAI/Client/ContentChunkType.cs:50]: Added additional unit tests to confirm the behaviour

**Review by westey-m — APPROVED** [review]

**Review by dmytrostruk — APPROVED** [review]
