### PR TITLE
.Net: Adding the ability to redirect system.Console output to test output.

### LINKED ISSUE #9009: .Net: Bug: No output when running the test. xUnit seems to be supressing the console output.
**Describe the bug**
xUnit seems to be supressing the console output.

**To Reproduce**
From VS Code:
1. From dotnet\samples\GettingStartedWithProcesses folder
2. dotnet test
3. Look at test output
Also, there is a typo on line #46
image

### PR DESCRIPTION
**Pull request by alliscode**
### Description

The PR adds the ability to redirect `system.Console` output to test output. The implementation requires a test to opt-in to this functionality so that existing tests will not change functionality by default.

***Why not just use `ITestOutputHelper ` or the `BaseTest` built in `WriteX(...)`?***

Because the process tests make use of several other classes that are writing console logs from within their functions. In order to use `ITestOutputHelper ` we would need to inject this object into those classes. While this is possible, it adds extra code that is unrelated to what the sample is demonstrating and increases the cognitive load on people using the samples to learn.

fixes #9009 

After this change, running Step01_Processes produces the following test output:

image

### Contribution Checklist

- [x] The code builds clean without any errors or warnings
- [x] The PR follows the [SK Contribution Guidelines](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md) and the [pre-submission formatting script](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md#development-scripts) raises no violations
- [x] All unit tests pass, and I have added new tests where possible
- [x] I didn't break anyone :smile:

### CODE REVIEW

File: dotnet/src/InternalUtilities/samples/InternalUtilities/BaseTest.cs [hunk 1]
```diff
@@ -59,7 +60,7 @@ protected Kernel CreateKernelWithChatCompletion()
         return builder.Build();
     }
 
-    protected BaseTest(ITestOutputHelper output)
+    protected BaseTest(ITestOutputHelper output, bool redirectSystemConsoleOutput = false)
```
Comment (crickman) [inline dotnet/src/InternalUtilities/samples/InternalUtilities/BaseTest.cs:63]: I'd be tempted to make the default `true`...I'm not sure any samples are using System.Console anyway.

**Review by crickman — APPROVED** [review]

File: dotnet/src/InternalUtilities/samples/InternalUtilities/BaseTest.cs (hunk 1 above)
Comment (alliscode) [reply dotnet/src/InternalUtilities/samples/InternalUtilities/BaseTest.cs:63]: I think I'll keep it opt-in for now, but if this is turns out to be a common issue then we can change it and make sure there are no side effects.

**Review by RogerBarreto — APPROVED** [review]

**Review by crickman — APPROVED** [review]
