### PR TITLE
.Net: Change Agents.Abstractions to depend on SemanticKernel.Abstractions instead of SemanticKernel.Core

### LINKED ISSUE #10571: .NET: Bug: Microsoft.SemanticKernel.Agents.Abstractions depends on Microsoft.SemanticKernel.Core
**Describe the bug**
It should just depend on Microsoft.SemanticKernel.Abstractions and any functionality that requires Microsoft.SemanticKernel.Core should move to the core agents package.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Platform**
 - Language: [e.g. C#, Python]
 - Source: [e.g. NuGet package version 0.1.0, pip package version 0.1.0, main branch of repository]
 - AI model: [e.g. OpenAI:GPT-4o-mini(2024-07-18)]
 - IDE: [e.g. Visual Studio, VS Code]
 - OS: [e.g. Windows, Mac]

**Additional context**

### PR DESCRIPTION
**Pull request by markwallace-microsoft**
### Motivation and Context

Closes #10571 

### Contribution Checklist

- [ ] The code builds clean without any errors or warnings
- [ ] The PR follows the [SK Contribution Guidelines](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md) and the [pre-submission formatting script](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md#development-scripts) raises no violations
- [ ] All unit tests pass, and I have added new tests where possible
- [ ] I didn't break anyone :smile:

### CODE REVIEW

File: dotnet/src/Agents/Core/ChatCompletionAgent.cs [hunk 1]
```diff
@@ -89,7 +89,7 @@ protected override Task<AgentChannel> RestoreChannelAsync(string channelState, C
     internal static (IChatCompletionService service, PromptExecutionSettings? executionSettings) GetChatCompletionService(Kernel kernel, KernelArguments? arguments)
     {
         // Need to provide a KernelFunction to the service selector as a container for the execution-settings.
-        KernelFunction nullPrompt = KernelFunctionFactory.CreateFromPrompt("placeholder", arguments?.ExecutionSettings?.Values);
+        KernelFunction nullPrompt = new KernelFunctionNoop(arguments?.ExecutionSettings);
```
Comment (westey-m) [inline dotnet/src/Agents/Core/ChatCompletionAgent.cs:92]: Instead of creating a noop function, should we not have an overload for SelectAIService that doesn't require a kernel function instead?  E.g maybe an overload that just takes ExecutionSettings if that is all that is actually required?

File: dotnet/src/Agents/Abstractions/KernelAgent.cs [hunk 2]
```diff
@@ -49,16 +46,10 @@ public abstract class KernelAgent : Agent
...
         if (this.Template == null)
         {
-            if (string.IsNullOrWhiteSpace(this.Instructions))
-            {
-                return null;
-            }
-
-            KernelPromptTemplateFactory templateFactory = new(this.LoggerFactory);
-            this.Template = templateFactory.Create(new PromptTemplateConfig(this.Instructions!));
+            return Task.FromResult<string?>(this.Instructions).Result;
```
Comment (westey-m) [inline dotnet/src/Agents/Abstractions/KernelAgent.cs:52]: Since `IPromptTemplateFactory` is in SK.Abstractions, can we not pass this in as a parameter or have it as a virtual property that if supplied can support templating?  Assuming templating of the default instructions is still desired.

File: dotnet/src/SemanticKernel.Abstractions/Functions/KernelFunctionNoop.cs [hunk 3]
```diff
@@ -0,0 +1,46 @@
...
+using System.Threading.Tasks;
+
+namespace Microsoft.SemanticKernel;
+
+/// <summary>
+/// Represents a kernel function that performs no operation.
+/// </summary>
+[RequiresUnreferencedCode("Uses reflection to handle various aspects of the function creation and invocation, making it incompatible with AOT scenarios.")]
+[RequiresDynamicCode("Uses reflection to handle various aspects of the function creation and invocation, making it incompatible with AOT scenarios.")]
+public sealed class KernelFunctionNoop : KernelFunction
```
Comment (dmytrostruk) [inline dotnet/src/SemanticKernel.Abstractions/Functions/KernelFunctionNoop.cs:17]: Even though the implementation is simple, should we mark it as experimental? Also, should we mention in XML doc what are the use cases for such function? I think such function could be useful for unit-testing.

**Review by dmytrostruk — APPROVED** [review]

File: dotnet/src/Agents/Abstractions/KernelAgent.cs (hunk 2 above)
Comment (markwallace-microsoft) [reply dotnet/src/Agents/Abstractions/KernelAgent.cs:52]: I'm not sure about templating the default instructions. There is an explicit `Template` property which can be used if templating is required. The problem with doing it automatically for the instructions is that we would also need a way to turn off this behaviour.

File: dotnet/src/SemanticKernel.Abstractions/Functions/KernelFunctionNoop.cs (hunk 3 above)
Comment (markwallace-microsoft) [reply dotnet/src/SemanticKernel.Abstractions/Functions/KernelFunctionNoop.cs]: I have made this internal

**Review by westey-m — APPROVED** [review]

File: dotnet/src/Agents/Core/ChatCompletionAgent.cs (hunk 1 above)
Comment (westey-m) [reply dotnet/src/Agents/Core/ChatCompletionAgent.cs]: Sounds good

File: dotnet/src/Agents/Abstractions/KernelAgent.cs (hunk 2 above)
Comment (westey-m) [reply dotnet/src/Agents/Abstractions/KernelAgent.cs:52]: Right, that makes sense.

**Comment by markwallace-microsoft** [comment]
Waiting on feedback from @crickman

File: dotnet/src/Agents/Abstractions/KernelAgent.cs (hunk 2 above)
Comment (crickman) [inline dotnet/src/Agents/Abstractions/KernelAgent.cs:52]: I believe this may be a regression.  We've previously supported users templating the raw `Instructions` with the understanding that is default to kernel-prompt-template.

Comment (markwallace-microsoft) [reply dotnet/src/Agents/Abstractions/KernelAgent.cs:52]: This change is intentional. For this to work the Agents abstractions need to depend on SK Core which is an anti-pattern. The current solution is hardcoded to the SK format which is problematic because we should support all template formats. My proposal is that we drop this and developers use the Template property if they want to use templating.

Comment (crickman) [reply dotnet/src/Agents/Abstractions/KernelAgent.cs:52]: That's fine as long as we understand it is a breaking change.  Honestly, I'd be suprised if it affects many, if any, customers.  At least we can update the sample so it isn't broken.x

Note: Ultimate, we _do_ support all formats.  For this one case we're discussing, it uses the default format in the absence of full template configuration.  Also it may be worth noting that for assistants or azure agents, Template initialization may not be so straightforward when retrieving an existing agent (versus creating a brand new definition).  That is, the `Instructions` property in the underlying model may be templatized based on the initial creation via `PromptTemplateConfig`.  High-order bit...there's several vectors to consider here that may not be entirely obvious.

Comment (crickman) [inline dotnet/src/Agents/Abstractions/KernelAgent.cs:52]: FWIW - Is `return this.Instructions;` problematic?

Comment (crickman) [reply dotnet/src/Agents/Abstractions/KernelAgent.cs:52]: We do currently support templating of `Instructions`... @westey-m is correct on his reading of the code.

Comment (markwallace-microsoft) [reply dotnet/src/Agents/Abstractions/KernelAgent.cs]: I have added in support for providing a template factory, this allows developers to optionally format the instructions if needed. We should consider dropping the Template property.

**Review by shethaadit — APPROVED** [review]

File: dotnet/src/Agents/Abstractions/KernelAgent.cs [hunk 4]
```diff
@@ -53,19 +58,21 @@ public abstract class KernelAgent : Agent
...
-        // If <see cref="Template"/> is not set, default instructions may be treated as "semantic-kernel" template.
-        if (this.Template == null)
+        // Use the provided template factory to format the instructions
+        if (this.TemplateFactory is not null && !string.IsNullOrEmpty(this.Instructions))
         {
-            if (string.IsNullOrWhiteSpace(this.Instructions))
-            {
-                return null;
-            }
+            var template = this.TemplateFactory.Create(new PromptTemplateConfig(this.Instructions!));
```
Comment (crickman) [inline dotnet/src/Agents/Abstractions/KernelAgent.cs:64]: Can we assign to `this.Template` here and then let the logic fall through to the existing render logic on lines 69-72?

File: dotnet/src/Agents/Abstractions/KernelAgent.cs (hunk 2 above)
Comment (crickman) [reply dotnet/src/Agents/Abstractions/KernelAgent.cs]: I like this.  Was thinking along similiar lines over night.  The `Template` property is manage internally as a performance optimization...once generated it can be re-used.

I wonder if the `TemplateFactory` property should have an `init` setter instead of `protected`?

Finally, I'm curious what you think about providing the `TemplateFormat` property for the new `PromptTemplateConfig` to match the provided factory.  (I've struggled with this not being discoverable on the `IPromptTemplateFactory` abstraction.

Comment (markwallace-microsoft) [reply dotnet/src/Agents/Abstractions/KernelAgent.cs]: After looking at the "Templating" samples I think the easiest thing to do is make `IPromptTemplateFactory` a required parameter if providing a `PromptTemplateConfig` so the behaviour is as follows:

1. If `PromptTemplateConfig` is provided then `IPromptTemplateFactory` is required.
2. If  `IPromptTemplateFactory` is missing or of wrong type then `KernelException` is thrown

File: dotnet/src/Agents/Abstractions/KernelAgent.cs [hunk 5]
```diff
@@ -53,19 +50,14 @@ public abstract class KernelAgent : Agent
     /// <returns>The formatted system instructions for the agent.</returns>
     protected async Task<string?> FormatInstructionsAsync(Kernel kernel, KernelArguments? arguments, CancellationToken cancellationToken)
     {
-        // If <see cref="Template"/> is not set, default instructions may be treated as "semantic-kernel" template.
-        if (this.Template == null)
+        // Use the provided template as the instructions
+        if (this.Template is not null)
```
Comment (crickman) [inline dotnet/src/Agents/Abstractions/KernelAgent.cs:54]: Were we going to change scope of `Template` to `protected`?

**Review by crickman — COMMENTED** [review]
Feels like we're still missing the case were an Azure Agent or Assistant was created with a template and the rehydrated from an existing model/definition via retrieval by its identifier.  

In that case, would the developer be expected to also provide the full template config?

What would be the behavior when the provided template config doesn't match this existing definition?

File: dotnet/src/Agents/Abstractions/KernelAgent.cs (hunk 2 above)
Comment (crickman) [reply dotnet/src/Agents/Abstractions/KernelAgent.cs]: This is sensible.  Please review my question about retrieving an existing assistant or azure-agent.

**Comment by markwallace-microsoft** [comment]
> Feels like we're still missing the case were an Azure Agent or Assistant was created with a template and the rehydrated from an existing model/definition via retrieval by its identifier.
> 
> In that case, would the developer be expected to also provide the full template config?
> 
> What would be the behavior when the provided template config doesn't match this existing definition?

This case needs to be handled as part of the declarative agent framework. My initial thought is that it should be possible to override instructions, provide additional tools, etc for an already deployed agent. Overriding instructions will be useful if the template contains values that are related to the current request.

**Review by crickman — APPROVED** [review]
