### PR TITLE
.Net: Adding Streaming Retry filter example

### LINKED ISSUE #10140: .Net: Guidance on how to retry a streaming response
The LLM may terminate unexpectedly during a streaming response. For non streaming responses a filter can be detect a failure and retry but this doesn't work for streaming responses.

### PR DESCRIPTION
**Pull request by RogerBarreto**
### Motivation and Context

- Resolve #10140

### CODE REVIEW

File: dotnet/samples/Concepts/Filtering/RetryWithFilters.cs [hunk 1]
```diff
@@ -69,4 +100,55 @@ public async Task OnFunctionInvocationAsync(FunctionInvocationContext context, F
...
+        private async IAsyncEnumerable<StreamingKernelContent> DeferredStreamingRetryResult(IAsyncEnumerable<StreamingKernelContent> results, FunctionInvocationContext context, Func<FunctionInvocationContext, Task> retry)
+        {
+            // I need to manually enumerate the results to catch the exception.
+            var enumerator = results.GetAsyncEnumerator();
+
+            while (true)
+            {
+                try
+                {
+                    if (!await enumerator.MoveNextAsync())
```
Comment (westey-m) [inline dotnet/samples/Concepts/Filtering/RetryWithFilters.cs:127]: From what I can tell it looks like if there is a failure half way through the stream we would have already returned some chunks and then start returning new chunks.  Is that expected?

**Review by westey-m — APPROVED** [review]

File: dotnet/samples/Concepts/Filtering/RetryWithFilters.cs (hunk 1 above)
Comment (RogerBarreto) [reply dotnet/samples/Concepts/Filtering/RetryWithFilters.cs:127]: This shows how a stream can be resilient, is a fair point, notably some messages can be sent to the client that the previous stream was interrupted and a new is attempted. 

For this scenario where the server fails for 401, this works best, I can add a comment regarding this scenario.

Ideally the filter should not buffer the stream and keep the streaming behavior as it goes.

**Review by dmytrostruk — APPROVED** [review]
