### PR TITLE
Fix parameter assignment in ActionPlanner

### LINKED ISSUE #997: Input confusion when ActionPlanner works with substep
**Describe the bug**
Input will show up in state. And then it will not be captured correctly into substep for action planner.

For example, for function name below, workspaceName could not be passed with correct input. It will get input from upstream. For example, user intent in chatapp.
We need to do custom coding to make it work.

public string GetDatasetName(string workspaceName)

User intent: I want to retrieve the names of datasets within a Power BI workspace named High_Memory.

{"state":[{"Key":"INPUT","Value":"High_Memory"}],"steps":[{"state":[{"Key":"INPUT","Value":""}],"steps":[],"parameters":[{"Key":"INPUT","Value":""}],"outputs":[],"next_step_index":0,"name":"GetDatasetName","skill_name":"PowerBI","description":"Return dataset name of my power bi workspace"}],"parameters":[{"Key":"INPUT","Value":""}],"outputs":[],"next_step_index":0,"name":"","skill_name":"Microsoft.SemanticKernel.Planning.Plan","description":"User intent: I want to retrieve the names of datasets within a Power BI workspace named High_Memory."}

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - IDE: [e.g. Visual Studio, VS Code]
 - NuGet Package Version [e.g. 0.1.0]

**Additional context**

### PR DESCRIPTION
**Pull request by lemillermicrosoft**
### Motivation and Context
This pull request fixes a bug in the ActionPlanner class where the plan parameters were not assigned correctly from the input parameters. It also updates some formatting

Fixes #997 

### Description
- Fix parameter assignment in ActionPlanner.CreatePlanFromParameters method
  - Use plan.Parameters instead of plan.State to assign the input parameters to the plan object
  - This fixes a bug where the plan state was overwritten by the input parameters, causing unexpected behavior and errors

### Contribution Checklist

- [x] The code builds clean without any errors or warnings
- [x] The PR follows SK Contribution Guidelines (https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md)
- [x] The code follows the .NET coding conventions (https://learn.microsoft.com/dotnet/csharp/fundamentals/coding-style/coding-conventions) verified with `dotnet format`
- [ ] All unit tests pass, and I have added new tests where possible
- [x] I didn't break anyone :smile:

### CODE REVIEW

File: dotnet/src/Extensions/Planning.ActionPlanner/ActionPlanner.cs [hunk 1]
```diff
@@ -126,7 +126,7 @@ public async Task<Plan> CreatePlanAsync(string goal)
         {
             if (p.Value != null)
             {
-                plan.State[p.Key] = p.Value.ToString();
+                plan.Parameters[p.Key] = p.Value.ToString();
```
Comment (teresaqhoang) [inline dotnet/src/Extensions/Planning.ActionPlanner/ActionPlanner.cs:129]: We'll need to change this in CP Chat WebApp whenever the nuget's are updated since it's checking for state. Can you add a TODO in PlanViewer?

**Review by shawncal — APPROVED** [review]
