### PR TITLE
.Net: [MEVD] Fix filtering by true

### LINKED ISSUE #13293: .Net: [MEVD] [SQL Server] Filter by true/false fails
```c#
[ConditionalFact]
public virtual Task True()
	=> this.TestFilterAsync(r => true, r => true, expectAllResults: true);

[ConditionalFact]
public virtual Task False()
	=> this.TestFilterAsync(r => false, r => false, expectZeroResults: true);
```

This is actually somewhat important, as filtering by true is the way to get all records from the collection.

### PR DESCRIPTION
**Pull request by roji**
Fixes #13293

### CODE REVIEW

File: dotnet/src/VectorData/Redis/RedisFilterTranslator.cs [hunk 1]
```diff
@@ -27,6 +27,14 @@ internal string Translate(LambdaExpression lambdaExpression, CollectionModel mod
         Debug.Assert(lambdaExpression.Parameters.Count == 1);
         this._recordParameter = lambdaExpression.Parameters[0];
 
+        // Weaviate doesn't seem to have a native way of expressing "always true" filters; since this scenario is important for fetching
```
Comment (westey-m) [inline dotnet/src/VectorData/Redis/RedisFilterTranslator.cs]:
```suggestion
        // Redis doesn't seem to have a native way of expressing "always true" filters; since this scenario is important for fetching
```

**Review by westey-m — APPROVED** [review]
