### PR TITLE
.Net: Fix issue 12775

### LINKED ISSUE #12775: .Net: Trouble using ResponseTool with Kernel Plugins
### Discussed in https://github.com/microsoft/semantic-kernel/discussions/12699

<div type='discussions-op-text'>

<sup>Originally posted by **thomasjlittle** July 10, 2025</sup>
Hi, I am trying to give an OpenAIResponseAgent access to Kernel plugins as well as the new ResponseTools (like file and web search) but it seems like as soon as I give the agent a ResponseTool, it loses access to the Kernel plugins, despite them getting loaded into the kernel. I am wondering if this is an issue with my implementation or if this is a bug. I will paste in a short code sample below that demonstrates this behavior.

This code sample is adapted from this [SK github sample](https://github.com/microsoft/semantic-kernel/blob/main/dotnet/samples/GettingStartedWithAgents/OpenAIResponse/Step04_OpenAIResponseAgent_Tools.cs).

Here is the code:
```csharp 
using System.ClientModel;
using ConsoleApp4;
using Microsoft.Extensions.Configuration;
using Microsoft.SemanticKernel;
using Microsoft.SemanticKernel.Agents.OpenAI;
using Microsoft.SemanticKernel.ChatCompletion;
using OpenAI.Responses;

var configuration = new ConfigurationBuilder()
    .AddJsonFile("appsettings.json")
    .Build();

await AddPluginsAsync();
async Task AddPluginsAsync()
{
    // Set vars
    string openAiKey = configuration["openAIKey"] ?? throw new InvalidOperationException("OpenAI key is not set in appsettings.json");
    
    // Create the responses agent 
    OpenAIResponseClient client = new OpenAIResponseClient("gpt-4.1", new ApiKeyCredential(openAiKey));
    OpenAIResponseAgent responseAgent = new(client);
    
    // Create a plugin that defines the tools to be used by the agent.
    KernelPlugin plugin = KernelPluginFactory.CreateFromType<MenuPlugin>();
    var tools = plugin.Select(f => f.ToToolDefinition(plugin.Name));
    responseAgent.Kernel.Plugins.Add(plugin);
    
    // Add a response tool
    ResponseCreationOptions creationOptions = new();
    creationOptions.Tools.Add(ResponseTool.CreateWebSearchTool());
    var options = new OpenAIResponseAgentInvokeOptions()
    {
        ResponseCreationOptions = creationOptions
    };

    ICollection<ChatMessageContent> messages =
    [
        new ChatMessageContent(AuthorRole.User, "What is the special soup and its price? Do not use the web search tool."),
        new ChatMessageContent(AuthorRole.User, "What is the special drink and its price?"),
    ];
    foreach (ChatMessageContent message in messages)
    {
        Console.WriteLine(message);
    }

    // Invoke the agent and output the response
    var responseItems = responseAgent.InvokeAsync(messages, options: options);
    await foreach (ChatMessageContent responseItem in responseItems)
    {
        Console.WriteLine(responseItem);
    }

}
```

where the MenuPlugin is copied from [here](https://github.com/microsoft/semantic-kernel/blob/main/dotnet/samples/GettingStartedWithAgents/Plugins/MenuPlugin.cs).

This code snippet returns something similar to the following:

> "What is the special soup and its price? Do not use the web search tool.
> What is the special drink and its price?
> I don't have access to live or local restaurant menus unless you provide them, so I can't give you the exact information about today's special soup or special drink and their prices without more context.
> 
> If you let me know the name of the restaurant or provide a menu, I can help you identify the special soup or drink and their prices! If you have a photo of the menu, you can upload it, and I'll assist you further."

However, when you remove the `options: options` param from the InvokeAsync call, it calls the menu plugin as expected.

I am using the following package versions:
Microsoft.SemanticKernel 1.60.0
Microsoft.SemanticKernel.Agents.OpenAI 1.60.0
Microsoft.SemanticKernel.Core 1.60.0
</div>

### PR DESCRIPTION
**Pull request by markwallace-microsoft**
### Motivation and Context

- Closes #12775 

### Contribution Checklist

- [ ] The code builds clean without any errors or warnings
- [ ] The PR follows the [SK Contribution Guidelines](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md) and the [pre-submission formatting script](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md#development-scripts) raises no violations
- [ ] All unit tests pass, and I have added new tests where possible
- [ ] I didn't break anyone :smile:

### CODE REVIEW

File: dotnet/src/Agents/OpenAI/Internal/ResponseCreationOptionsFactory.cs [hunk 1]
```diff
@@ -16,28 +16,43 @@ internal static ResponseCreationOptions CreateOptions(
...
+        var instructions = $"{agent.Instructions}{(string.IsNullOrEmpty(agent.Instructions) || string.IsNullOrEmpty(invokeOptions?.AdditionalInstructions) ? "" : "\n")}{invokeOptions?.AdditionalInstructions}";
+        ResponseCreationOptions creationOptions;
         if (invokeOptions is OpenAIResponseAgentInvokeOptions responseAgentInvokeOptions &&
             responseAgentInvokeOptions.ResponseCreationOptions is not null)
         {
-            // Use the options provided by the caller
-            return responseAgentInvokeOptions.ResponseCreationOptions;
+            creationOptions = new ResponseCreationOptions
+            {
+                EndUserId = responseAgentInvokeOptions.ResponseCreationOptions.EndUserId ?? agent.GetDisplayName(),
```
Comment (dmytrostruk) [inline dotnet/src/Agents/OpenAI/Internal/ResponseCreationOptionsFactory.cs:26]: nit: I'm wondering, how `EndUserId` is related to agent display name?

**Review by dmytrostruk — APPROVED** [review]

File: dotnet/src/Agents/OpenAI/Internal/ResponseCreationOptionsFactory.cs (hunk 1 above)
Comment (markwallace-microsoft) [reply dotnet/src/Agents/OpenAI/Internal/ResponseCreationOptionsFactory.cs:26]: The end user id allows us to identify who is sending the request. This allows OpenAI to provide more actionable feedback in the event that they detect any policy violations in the application.

See: https://platform.openai.com/docs/guides/safety-best-practices#end-user-ids

**Comment by markwallace-microsoft** [comment]
Unrelated integration tests failure

```
  Failed SemanticKernel.IntegrationTests.Connectors.AzureOpenAI.AzureOpenAITextToImageTests.GetImageContentsCanReturnImageUrlAsync [1 s]
  Error Message:
   Microsoft.SemanticKernel.HttpOperationException : HTTP 400 (invalid_request_error: content_policy_violation)

Your request was rejected as a result of our safety system. Your prompt may contain text that is not allowed by our safety system.
```
