### PR TITLE
.Net: Fixes Qdrant 1.17 issue with returning empty vectors

### LINKED ISSUE #13587: .Net: Bug: Wrong input: Vector dimension error: expected dim: 3072, got 0 with qdrant server 1.17.0
**Describe the bug**
Getting GprcExceptions with latest qdrant version 1.17 due to changes in grpc api

```
	5 unhandled exceptions: 02/21/2026 00:27:07 +00:00: Microsoft.Extensions.VectorData.VectorStoreException: Call to vector store failed.
---> Grpc.Core.RpcException: Status(StatusCode="InvalidArgument", Detail="Wrong input: Vector dimension error: expected dim: 3072, got 0")
at Qdrant.Client.QdrantClient.UpsertAsync(UpsertPoints request, CancellationToken cancellationToken)
at Qdrant.Client.QdrantClient.UpsertAsync(String collectionName, IReadOnlyList`1 points, Filter updateFilter, Boolean wait, Nullable`1 ordering, ShardKeySelector shardKeySelector, CancellationToken cancellationToken)
at Microsoft.Extensions.VectorData.VectorStoreErrorHandler.RunOperationAsync[TResult,TException](VectorStoreCollectionMetadata metadata, String operationName, Func`1 operation)
--- End of inner exception stack trace ---
at Microsoft.Extensions.VectorData.VectorStoreErrorHandler.RunOperationAsync[TResult,TException](VectorStoreCollectionMetadata metadata, String operationName, Func`1 operation)
at Microsoft.SemanticKernel.Connectors.Qdrant.QdrantCollection`2.UpsertAsync(IEnumerable`1 records, CancellationToken cancellationToken)
at Microsoft.SemanticKernel.Connectors.Qdrant.QdrantCollection`2.UpsertAsync(TRecord record, CancellationToken cancellationToken)
at MyProjectName.Handles.MetadataHandler.Handle(MetadataUpdate`1 command) in /home/vsts/work/1/s/src/MyProjectName/Handles/MetadataHandler.cs:line 70
at Rebus.Pipeline.Receive.HandlerInvoker`1.Invoke()
at Rebus.Diagnostics.Incoming.HandlerInvokerWrapper.Invoke()
at Rebus.Pipeline.Receive.DispatchIncomingMessageStep.Process(IncomingStepContext context, Func`1 next)
at Rebus.Sagas.LoadSagaDataStep.Process(IncomingStepContext context, Func`1 next)
at Rebus.Pipeline.Receive.ActivateHandlersStep.Process(IncomingStepContext context, Func`1 next)
at Rebus.Pipeline.Receive.HandleRoutingSlipsStep.Process(IncomingStepContext context, Func`1 next)
at Rebus.Pipeline.Receive.DeserializeIncomingMessageStep.Process(IncomingStepContext context, Func`1 next)
at Rebus.DataBus.ClaimCheck.HydrateIncomingMessageStep.Process(IncomingStepContext context, Func`1 next)
at Rebus.Pipeline.Receive.HandleDeferredMessagesStep.Process(IncomingStepContext context, Func`1 next)
at Rebus.Retry.Simple.DefaultRetryStep.Process(IncomingStepContext context, Func`1 next)
```

**To Reproduce**
1. Install Qdrant 1.16.3 (via Docker or Kubernetes)
2. Setup example project
    ```csharp
        VectorStoreCollection<ulong, VectorModels.Project> projects = await GetProjectsCollection();
        VectorModels.Project? project = await projects.GetAsync((ulong)projectId, new()
        {
            IncludeVectors = true // This worked before
        });
        if (project is null)
        {
           // log not found
            return;
        }
        await projects.UpsertAsync(project);
    ``` 

3. It will work
4. Upgrade to Qdrant 1.17.0
5. Run again. Exception will be thrown.
6. Downgrading to Qdrant 1.16.3 doesn't make it work either (beats me) 

**Expected behavior**
Vectors to be loaded and metadata (which are not affected by vectors, as they are merely used for filtering and additional information) to be fetched correctly and sent with the upsert 

**Platform**
 - Language: C#
 - Source: NuGet, Version 1.72 with the corresponding Qdrant connector 
 - AI model: No model required for this (updating metadata only)
 - IDE: Visual Studio 2026
 - OS: Developmnet Windows, Application runs in Docker on .NET 10 and k8s

**Additional context**
 
- Downgrading to Qdrant 1.16.3 doesn't unlock, error still persists
- Upgrading transient Dependency of `Qdrant.Client` to latest version `1.17.0` did not fix it either.

### PR DESCRIPTION
**Pull request by TsengSR**
### Motivation and Context

With Qdrant server 1.17 Embeddings stopped being returned.  

Fixes #13587

### Description

The `VectorOutput.Data` property became deprecated in `Qdrant.Client` 1.17. The alternative is to use `VectorOutput.Dense.Data` instead or `VectorOutput.GetDenseVector()` (from `Qdrant.Client` 1.16.0 or later). 

Since the `.Dense` already exyists in `Qdrant.Client` 1.15.1 that is used by the current connector, I used these. The `.GetDenseVector()` also returns nullable `DenseVector`, so I was unsure how to handle in context of Semantic Kernel, as as far as I see it Semantic Kernel only supports Dense Vectors (the other two are `.Sparse` for sparse vectors and `.MultiDense`).

So this may need special handling in future to throw an exception, when the server returns one of the other two vector types and not dense vectors.

### Contribution Checklist

- [x] The code builds clean without any errors or warnings
- [x] The PR follows the [SK Contribution Guidelines](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md) and the [pre-submission formatting script](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md#development-scripts) raises no violations
- [ ] All unit tests pass, and I have added new tests where possible
- [ ] I didn't break anyone :smile:

I'm currently unable (or rather I don't know how) to run the local integration/unit tests against  the qdrant database. But I validated the change in my personal project mentioned in #13587 by directly referencing the connector in my project and it correctly returned the vectors on the sample code where it failed previously

```csharp
    VectorStoreCollection<ulong, VectorModels.Project> projects = await GetProjectsCollection();
    VectorModels.Project? project = await projects.GetAsync((ulong)projectId, new()
    {
        IncludeVectors = true
    });

    // project at this poind hat 0 sized Embedding property
    if (project is null)
    {
        return;
    }
    await projects.UpsertAsync(project);
```

### CODE REVIEW

**Comment by westey-m** [comment]
Thanks @TsengSR, seems like a straightforward enough change.  The integration tests automatically spin up a qdrant container in docker to test against locally.  So running the tests should do all the work, as long as you have docker installed.
They also run during the PR merge process, so we can check then if nothing has regressed.

Looks like a few of the unit tests need updating though to match the latest code.

File: dotnet/src/VectorData/Qdrant/QdrantMapper.cs [hunk 1]
```diff
@@ -134,9 +134,9 @@ static void PopulateVectorProperty(TRecord record, VectorOutput value, VectorPro
                     record,
                     (Nullable.GetUnderlyingType(property.Type) ?? property.Type) switch
                     {
-                        var t when t == typeof(ReadOnlyMemory<float>) => new ReadOnlyMemory<float>(value.Data.ToArray()),
-                        var t when t == typeof(Embedding<float>) => new Embedding<float>(value.Data.ToArray()),
-                        var t when t == typeof(float[]) => value.Data.ToArray(),
+                        var t when t == typeof(ReadOnlyMemory<float>) => new ReadOnlyMemory<float>(value.Dense.Data.ToArray()),
+                        var t when t == typeof(Embedding<float>) => new Embedding<float>(value.Dense.Data.ToArray()),
+                        var t when t == typeof(float[]) => value.Dense.Data.ToArray(),
```
Comment (westey-m) [inline dotnet/src/VectorData/Qdrant/QdrantMapper.cs]: Do we also need to update line 80, where the mapping to the qdrant storage type happens?

**Comment by TsengSR** [comment]
Okay, seems the test can run (net472 fails, seems tls validation issue with the qdrant store), but there seems to be issues. 

The containers spinning up during the tests are qdrant 1.13.4 (shows under the qdrant logo, when they spin up) which probably still only suports the old format. I had 1.16.3 previously and upgraded to 1.17 when it happened.

But all I could find is 

https://github.com/microsoft/semantic-kernel/blob/4d675929578f8a07dfdff5361533d362f628d571/dotnet/samples/Concepts/Memory/VectorStoreFixtures/VectorStoreInfra.cs#L65-L72

which should be 1.17.0, but its not what runs in the container. Any ideas/pointers?

**Comment by westey-m** [comment]
@TsengSR, check out https://github.com/microsoft/semantic-kernel/blob/main/dotnet/test/VectorData/Qdrant.ConformanceTests/Support/QdrantTestStore.cs#L21.

We use https://testcontainers.com/modules/qdrant/?language=dotnet.  I see we don't pass a version into QdrantBuilder, so I would have expected it to use the latest version, but I guess not.  It's possible to pass a specific version though:
```csharp
var qdrantContainer = new QdrantBuilder("qdrant/qdrant:v1.13.4")
  .Build();
```

The code you shared is actually samples, but the tests are all under https://github.com/microsoft/semantic-kernel/blob/main/dotnet/test/VectorData

File: dotnet/test/VectorData/Weaviate.ConformanceTests/Support/TestContainer/WeaviateBuilder.cs [hunk 2]
```diff
@@ -31,8 +31,8 @@ protected override WeaviateBuilder Init()
             .WithEnvironment("AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED", "true")
             .WithEnvironment("PERSISTENCE_DATA_PATH", "/var/lib/weaviate")
             .WithWaitStrategy(Wait.ForUnixContainer()
-                .UntilPortIsAvailable(WeaviateHttpPort)
-                .UntilPortIsAvailable(WeaviateGrpcPort)
+                .UntilInternalTcpPortIsAvailable(WeaviateHttpPort)
+                .UntilInternalTcpPortIsAvailable(WeaviateGrpcPort)
```
Comment (TsengSR) [inline dotnet/test/VectorData/Weaviate.ConformanceTests/Support/TestContainer/WeaviateBuilder.cs:35]: `.UnitPortIsAvailable` was removed in Testcontainers/TestContainers.Qdrant 4.7.0 (I needed a newer version to use `new QdrantBuilder("qdrant/qdrant:v1.17.0").Build();` as 4.6.0 only had a parameterless constructor).

I'm honestly not sure which one is the correct replacement, as the documentation doesn't state it, but this [PR](https://github.com/testcontainers/testcontainers-dotnet/pull/1528/changes/80a270f6168e83e74711dfc3d6f7f1482ac55aab) where it was removed, suggests its the internal, though they use both in some places. 

In my local machine all the of the Weaviate test suits did run green with both `UntilInternalTcpPortIsAvailable` and `UntilExternalTcpPortIsAvailable`

**Comment by TsengSR** [comment]
> @TsengSR, check out https://github.com/microsoft/semantic-kernel/blob/main/dotnet/test/VectorData/Qdrant.ConformanceTests/Support/QdrantTestStore.cs#L21.
> 
> We use https://testcontainers.com/modules/qdrant/?language=dotnet. I see we don't pass a version into QdrantBuilder, so I would have expected it to use the latest version, but I guess not. It's possible to pass a specific version though:
> 
> ```cs
> var qdrantContainer = new QdrantBuilder("qdrant/qdrant:v1.13.4")
>   .Build();
> ```
> 
> The code you shared is actually samples, but the tests are all under https://github.com/microsoft/semantic-kernel/blob/main/dotnet/test/VectorData

Thanks, that helped a lot. The current Testcontainers.Qdrant didn't had any constructor, updated to 4.10.0 locally which contain these (and deprecates the parameterless one). Its still odd ":latest" tag gave v1.16.3, but ":v1.17.0" pulled the correct image. 

Had to change the setup slightly for Weaviate Tests, as `UntilPortIsAvailable` was removed, see comment. 

Fixed the test issues by doing pattern matching whether `.Dense` is null or not and otherwise fall back to `.Data`. `.Data` will eventually be removed at some point in future as its deprecated from `Qdrant.Client: 1.16.0` onwards, but for l left the Qdrant.Client at `1.15.1`

**update**:
One thing I noticed is that `QdrantUnitTests` don't run against the database and something internally sets the `VectorOutput.Data`, so these tests were failing when not having the `{ Data: not null} =>` fall back. Didn't bother yet to look where that happens, but its something to consider when `VectorOutput.Data` gets removed eventually.

File: dotnet/global.json [hunk 3]
```diff
@@ -1,6 +1,5 @@
 {
   "sdk": {
-    "version": "10.0.100",
```
Comment (roji) [inline dotnet/global.json:3]: Why this removal? I think we should have an explicit version here.

File: dotnet/test/VectorData/Qdrant.ConformanceTests/Support/QdrantTestStore.cs [hunk 4]
```diff
@@ -18,7 +18,7 @@ internal sealed class QdrantTestStore : TestStore
     // Qdrant doesn't support the default Flat index kind
     public override string DefaultIndexKind => IndexKind.Hnsw;
 
-    private readonly QdrantContainer _container = new QdrantBuilder().Build();
+    private readonly QdrantContainer _container = new QdrantBuilder("qdrant/qdrant:v1.17.0").Build();
```
Comment (roji) [inline dotnet/test/VectorData/Qdrant.ConformanceTests/Support/QdrantTestStore.cs:21]: I think the intention here was to have `latest`, which does exist (I'm surprised that isn't the default when leaving out the parameter).

Though for reproducible, stable builds pinning to a specific version as here is better, this way we don't get failing builds because a new qdrant container version is released with some breaking changes. So am OK to do the proposed change.

**Review by roji — COMMENTED** [review]
LGTM, but see the global.json change.

File: dotnet/global.json (hunk 3 above)
Comment (TsengSR) [reply dotnet/global.json:3]: Sorry, that was an accident. Some stuff failed to compile so I removed it, but accidentally added it to the commit

File: dotnet/test/VectorData/Qdrant.ConformanceTests/Support/QdrantTestStore.cs (hunk 4 above)
Comment (TsengSR) [reply dotnet/test/VectorData/Qdrant.ConformanceTests/Support/QdrantTestStore.cs:21]: having ":latest" did pull 1.16.3 on my machine. No idea why. Docker hub clearly points latest to 1.17. Also I think the change should need a dual test with 1.17 and an version older than that but I don't think thats easily done w/o bigger changes to the integration tests. `Testcontainers.Qdrant: 4.6.0` even pulled `v1.13.4`

Comment (roji) [reply dotnet/test/VectorData/Qdrant.ConformanceTests/Support/QdrantTestStore.cs:21]: Really weird... In any case, as I wrote I think it's OK to pin to a specific version and bump manually for deterministic builds.

**Review by roji — APPROVED** [review]
LGTM, thanks!

@westey-m waiting for your approval now.

**Comment by roji** [comment]
@TsengSR see build error in CI.

**Comment by TsengSR** [comment]
> @TsengSR see build error in CI.

Fixed that. There are 4 tests failing on pinecone, but this also fail when I run them against main branch. Not sure its related to my machine setup. For qdrant net472 most fail too, but net10 they succeed. Hope it will work though. 

image

File: dotnet/src/VectorData/Qdrant/QdrantMapper.cs (hunk 1 above)
Comment (westey-m) [reply dotnet/src/VectorData/Qdrant/QdrantMapper.cs]: @TsengSR, one more comment here, that's worth double checking.

Comment (TsengSR) [reply dotnet/src/VectorData/Qdrant/QdrantMapper.cs]: In my testing it didn't seem to be necessary.
Inserting (and updating after the fix) worked fine.

The only issue that was happening seems to be that the Vector data were empty on get/find, which then sent an empty vector in update and failed (due to dimensions being 0 instead of expected 3072).

The [release notes](https://github.com/qdrant/qdrant/releases) of qdrant 1.17.0 also only mention change in the response format for gRPC.

**Comment by westey-m** [comment]
FYI, work is in progress to fix the integration test failures. There are some models that got deprecated that requires updates.
